### ISSUE TITLE
Unable to open JPM View

### ISSUE THREAD

**Issue by diamondq** [bndtools/bndtools#1020]
Started seeing this message in my Eclipse. Tried updating to the latest (3.0.0-DEV-20150215-183320-g5f641f7), but still seeing it, whenever I attempt to go to the JPM View.

```
java.lang.AbstractMethodError: aQute.bnd.jpm.Repository.browse(Ljava/lang/String;)Ljava/net/URI;
	at org.bndtools.core.views.jpm.JPMBrowserView.handleWorkbenchSelection(JPMBrowserView.java:156)
	at org.bndtools.core.views.jpm.JPMBrowserView.selectionChanged(JPMBrowserView.java:143)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:218)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.handleSelectionChanged(SelectionService.java:107)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.access$0(SelectionService.java:91)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService$1.selectionChanged(SelectionService.java:66)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$2.run(SelectionAggregator.java:125)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.notifyListeners(SelectionAggregator.java:122)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.access$5(SelectionAggregator.java:119)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$7$1.run(SelectionAggregator.java:232)
	at org.eclipse.e4.core.contexts.RunAndTrack.runExternalCode(RunAndTrack.java:56)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$7.changed(SelectionAggregator.java:229)
... (many many more lines)

```

Running Eclipse 4.4
```
eclipse.buildId=4.4.1.M20140925-0400
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product
```

**Comment by bjhargrave** [comment]
https://github.com/bndtools/bnd/pull/780 updated `SearchableRepository` to add a browse method. The jpm repo you are using seems out of date since it does not implement this new method. Do you see this on a clean install of Eclipse/bndtools? I am wondering if p2 is using an older version of biz.aQute.repository in your Eclipse?

**Comment by bjhargrave** [comment]
Also, the released biz.aQute.repository jar has a bad import version range for aQute.bnd.service.repository of "[1.2,2)". It should have been "[1.2.,1.3)" since the repository jar implements a Provider Type from that package. The dev (3.0) version of the biz.aQute.repository jar has the correct import version range of "[1.3,1.4)".

So it is possible that p2 has configured eclipse to use an older version of biz.aQute.repository jar (even though you updated to the dev 3.0 build) and the older jar is importing the 1.3 version of the aQute.bnd.service.repository because it has a faulty import version range.

This is why I asked you to try a fresh eclipse install with a fresh 3.0 bndtools install to see if you still get the problem.

**Comment by diamondq** [comment]
Unfortunately, still getting it. Here's the versions of what I have installed. Although not a completely fresh Eclipse install, since I've got a couple of other tools installed (like Apache Ivy).

![Imgur](http://i.imgur.com/3oJQRW4.png)

**Comment by bjhargrave** [comment]
Can you check the plugins folder for your eclipse installation to make sure there are no other biz.aQute.* non-3.0 jars in there?

I looked through all the jars which are part of the current bndtools 3.0 build and there is only the 1.3 version of the `aQute.bnd.service.repository` package. It is exported by biz.aQute.bndlib 3.0 and imported by bndtools.core 3.0 and biz.aQute.repository 3.0.
