### ISSUE TITLE
"Error initialising bnd launcher" when starting a bndrun file

### ISSUE THREAD

**Issue by marcdejonge** [bndtools/bndtools#1056]
On another machine than my own, I've shared a bnd-based project. On this specific machine we see the following error when running a bndrun file. It all works fine on my own machine.

```
Status ERROR: bndtools.core code=0 Error initialising bnd launcher java.lang.IllegalArgumentException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
java.lang.IllegalArgumentException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
	at aQute.bnd.build.Project.getHandler(Project.java:2216)
	at aQute.bnd.build.Project.getProjectLauncher(Project.java:2177)
	at bndtools.launch.OSGiRunLaunchDelegate.initialiseBndLauncher(OSGiRunLaunchDelegate.java:65)
	at bndtools.launch.AbstractOSGiLaunchDelegate.buildForLaunch(AbstractOSGiLaunchDelegate.java:50)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:855)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

Both machines are running Eclipse 4.4.1 with bndtools 2.4.1-REL. We've also tried a completely clean checkout from git, but it won't help. The only difference I see is that his laptop is running Windows 8 and mine is Windows 7.

Any ideas what may be wrong? What can cause this error?

ps. I did see this exact stacktrace in issue #517, but no solution has ever been proposed. Also, we don't use the maven plugin, but only local and fixed repos.

**Comment by marcdejonge** [comment]
Anyone? We still have this issue and that means that this machine is not usable for development.

Can anyone explain the message at all? I've got no idea where to start looking.

**Comment by bjhargrave** [comment]
It means that biz.aQute.bndlib cannot find the launcher code in biz.aQute.launcher. In bndtools, biz.aQute.launcher is packaged in a fragment bundle called org.bndtools.embedded repo which must be installed and attached to the biz.aQute.bndlib bundle. Look in the Eclipse installations and make sure this is the case.

**Comment by marcdejonge** [comment]
It seems that a clean install fixed this problem. Now we've hit an new problem, see issue #1055 

Could there be something wrong with the current release in the eclipse marketplace?
