### ISSUE TITLE
Resolver fails when bundle contains native library

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1059]
If you add a bundle to the Run Requirements that contains a native library with the manifest header:
```
Bundle-NativeCode: lib/osx/libio.serial.native.dylib; osname=macosx; processor=x86_64
```
you get:

```
org.osgi.service.resolver.ResolutionException: Unable to resolve <<INITIAL>> version=null: missing requirement Require[osgi.identity]{}{filter=(osgi.identity=net.springfieldusa.io.serial)} [caused by: Unable to resolve net.springfieldusa.io.serial version=0.0.0.201503050226: missing requirement Require[osgi.native]{}{filter=(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86_64))}]
org.osgi.service.resolver.ResolutionException: org.osgi.service.resolver.ResolutionException: Unable to resolve <<INITIAL>> version=null: missing requirement Require[osgi.identity]{}{filter=(osgi.identity=net.springfieldusa.io.serial)} [caused by: Unable to resolve net.springfieldusa.io.serial version=0.0.0.201503050226: missing requirement Require[osgi.native]{}{filter=(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86_64))}]
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:48)
	at org.bndtools.core.resolve.ResolveOperation.run(ResolveOperation.java:87)
	at org.bndtools.core.resolve.ResolveJob.run(ResolveJob.java:57)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.osgi.service.resolver.ResolutionException: Unable to resolve <<INITIAL>> version=null: missing requirement Require[osgi.identity]{}{filter=(osgi.identity=net.springfieldusa.io.serial)} [caused by: Unable to resolve net.springfieldusa.io.serial version=0.0.0.201503050226: missing requirement Require[osgi.native]{}{filter=(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86_64))}]
	at biz.aQute.resolve.ResolveProcess.augment(ResolveProcess.java:157)
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:133)
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:45)
	... 3 more
```

**Comment by timothyjward** [comment]
This is actually working properly as the native code header adds a platform specific requirement to the bundle. 

You need to give Bndtools a little bit more information in the bndrun file to allow these requirements to be satisfied. Basically the resolver needs to know which platform you intend to run on.

If you want to resolve against the "current" platform, i.e. the same computer that you are running Bndtools on, then you can use the following:

    -runsystemcapabilities: ${native_capability}

The ${native_capability} macro expands to an osgi.native capability based on the computer in front of you. For example if you do this on a Mac then it will expand to something like "osgi.native; osgi.native.osname=MacOS; osgi.native.process=x86_64"... and so on.

If you need to do the resolution for some other computer, then you need to specify the native capability manually. For example in order to resolve for Linux/x86_64 then you can say this:

    -runsystemcapabilities: osgi.native; osgi.native.osname=Linux; osgi.native.processor=x86_64.

**Comment by fhuberts** [comment]
I thought I put this in the templates? Like years ago...

**Comment by fhuberts** [comment]
Here it is: 39eb776733467f287616a30a95b5ecf4f2cace34, 2013-05-29 18:21:21

**Comment by njbartlett** [comment]
@fhuberts Certainly, but it's not in every template, and it's always possible that the user has removed it (especially as almost nobody knows what it does...)
