### ISSUE TITLE
Bndtools with fresh workspace: Path must include project and resource name: /foo.bar

### ISSUE THREAD

**Issue by seanbright** [bndtools/bndtools#1069]
Eclipse Standard/SDK (Version: Luna Service Release 2 (4.4.2) / Build id: 20150219-0600)
Bndtools 3.0.0.DEV-20150310-113217-gcbb07d5

* Fresh workspace
* New > Bndtools OSGi Project
* Project name: foo.bar (everything else defaults)
* Template: OSGi Standard Templates - Component Development (everything else defaults)

![image](https://cloud.githubusercontent.com/assets/114601/6579170/e24e326c-c71e-11e4-8208-008162ec8e74.png)

The cnf project wizard doesn't come up, but can be created manually afterwards.

**Comment by bjhargrave** [comment]
Was there an exception in the Error Log?

**Comment by seanbright** [comment]
That would help I suppose.  This is the first of a few.  Let me know if you need more.

eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product

bndtools.builder
Error
Tue Mar 10 15:20:47 EDT 2015
Unable to get bnd project for project foo.bar

java.lang.IllegalArgumentException: No Workspace found from: C:\Users\sbright\jersey
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:154)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:107)
	at bndtools.central.Central.getWorkspace(Central.java:242)
	at bndtools.central.Central.getProject(Central.java:545)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.<init>(BndContainerInitializer.java:161)
	at org.bndtools.builder.classpath.BndContainerInitializer.initialize(BndContainerInitializer.java:80)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:2902)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:1937)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3247)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.create(CPListElement.java:593)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.create(CPListElement.java:578)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.BuildPathsBlock.getCPListElements(BuildPathsBlock.java:423)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.BuildPathsBlock.init(BuildPathsBlock.java:327)
	at org.eclipse.jdt.ui.wizards.JavaCapabilityConfigurationPage.init(JavaCapabilityConfigurationPage.java:151)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo.initializeBuildPath(NewJavaProjectWizardPageTwo.java:318)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo.updateProject(NewJavaProjectWizardPageTwo.java:252)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo.access$2(NewJavaProjectWizardPageTwo.java:200)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo$1UpdateRunnable.run(NewJavaProjectWizardPageTwo.java:161)
	at org.eclipse.ui.actions.WorkspaceModifyDelegatingOperation.execute(WorkspaceModifyDelegatingOperation.java:69)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:106)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:118)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by bjhargrave** [comment]
That is not the exception I need. That is just logged and not thrown. (I may want to not log it since it may happen when the first project is created in an empty workspace. Was there a cnf project already?) 

I need the exception for "Path must include project and resource name".

**Comment by seanbright** [comment]
No, it was a fresh workspace (nothing in it).

Here is the other Path exception:

<pre>
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product

org.eclipse.core.resources
Error
Tue Mar 10 15:37:18 EDT 2015
Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".

org.eclipse.core.runtime.CoreException: Build Error!
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:268)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalArgumentException: Path must include project and resource name: /foo.bar
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2137)
	at org.eclipse.core.internal.resources.Container.getFile(Container.java:167)
	at org.bndtools.build.api.AbstractBuildErrorDetailsHandler.getDefaultResource(AbstractBuildErrorDetailsHandler.java:67)
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:130)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:121)
	... 12 more
</pre>

And:

<pre>
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product

bndtools.builder
Error
Tue Mar 10 15:37:18 EDT 2015
Build Error!

java.lang.IllegalArgumentException: Path must include project and resource name: /foo.bar
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2137)
	at org.eclipse.core.internal.resources.Container.getFile(Container.java:167)
	at org.bndtools.build.api.AbstractBuildErrorDetailsHandler.getDefaultResource(AbstractBuildErrorDetailsHandler.java:67)
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:130)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:121)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</pre>

**Comment by bjhargrave** [comment]
> java.lang.IllegalArgumentException: Path must include project and resource name: /foo.bar at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63) at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2137) at org.eclipse.core.internal.resources.Container.getFile(Container.java:167) at org.bndtools.build.api.AbstractBuildErrorDetailsHandler.getDefaultResource(AbstractBuildErrorDetailsHandler.java:67) at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:130) at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:121)

@pkriens This is in the marker support.

**Comment by bjhargrave** [comment]
Also, why isn't the cnf project created? Perhaps because of these errors?

**Comment by bjhargrave** [comment]
> Also, why isn't the cnf project created? Perhaps because of this errors?

Yes. The build listener which would create cnf is not called because the builder fails with NPE before the builder can run. Marker support needs to fix its exception before the builder will get to the point of notifying the listener to create cnf.

The builder is trying to get the bnd Project but can't because there is no workspace. It then tries to set a marker because there is not workspace but marker support requires a workspace, so death....

**Comment by seanbright** [comment]
After your PR, here is the latest full log from a session.

<pre>
!SESSION 2015-03-10 17:42:55.561 -----------------------------------------------
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product

!ENTRY bndtools.builder 1 0 2015-03-10 17:43:29.830
!MESSAGE Unable to get bnd project for project foo.bar
!STACK 0
java.lang.IllegalArgumentException: No Workspace found from: C:\Users\sbright\jersey
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:154)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:107)
	at bndtools.central.Central.getWorkspace(Central.java:242)
	at bndtools.central.Central.getProject(Central.java:545)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.<init>(BndContainerInitializer.java:161)
	at org.bndtools.builder.classpath.BndContainerInitializer.initialize(BndContainerInitializer.java:80)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:2902)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:1937)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3247)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.create(CPListElement.java:593)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.create(CPListElement.java:578)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.BuildPathsBlock.getCPListElements(BuildPathsBlock.java:423)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.BuildPathsBlock.init(BuildPathsBlock.java:327)
	at org.eclipse.jdt.ui.wizards.JavaCapabilityConfigurationPage.init(JavaCapabilityConfigurationPage.java:151)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo.initializeBuildPath(NewJavaProjectWizardPageTwo.java:318)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo.updateProject(NewJavaProjectWizardPageTwo.java:252)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo.access$2(NewJavaProjectWizardPageTwo.java:200)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo$1UpdateRunnable.run(NewJavaProjectWizardPageTwo.java:161)
	at org.eclipse.ui.actions.WorkspaceModifyDelegatingOperation.execute(WorkspaceModifyDelegatingOperation.java:69)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:106)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:118)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY bndtools.core 4 0 2015-03-10 17:43:31.371
!MESSAGE Unable to create BndEditModel with Workspace, defaulting to without Workspace
!STACK 0
java.lang.IllegalArgumentException: No Workspace found from: C:\Users\sbright\jersey
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:154)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:107)
	at bndtools.central.Central.getWorkspace(Central.java:242)
	at bndtools.wizards.project.AbstractNewBndProjectWizard.generateBndModel(AbstractNewBndProjectWizard.java:86)
	at bndtools.wizards.project.NewBndProjectWizard.generateBndModel(NewBndProjectWizard.java:67)
	at bndtools.wizards.project.AbstractNewBndProjectWizard$1.run(AbstractNewBndProjectWizard.java:181)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:466)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:374)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1059)
	at bndtools.wizards.project.AbstractNewBndProjectWizard.performFinish(AbstractNewBndProjectWizard.java:174)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:853)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:438)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
	at org.eclipse.jface.window.Window.open(Window.java:808)
	at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:136)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

!ENTRY org.eclipse.core.resources 4 2 2015-03-10 17:43:31.865
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 1
org.eclipse.core.runtime.CoreException: Build Error!
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:268)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalArgumentException: Path must include project and resource name: /foo.bar
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2137)
	at org.eclipse.core.internal.resources.Container.getFile(Container.java:167)
	at org.bndtools.build.api.AbstractBuildErrorDetailsHandler.getDefaultResource(AbstractBuildErrorDetailsHandler.java:67)
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:130)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:121)
	... 12 more
!SUBENTRY 1 bndtools.builder 4 0 2015-03-10 17:43:31.867
!MESSAGE Build Error!
!STACK 0
java.lang.IllegalArgumentException: Path must include project and resource name: /foo.bar
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2137)
	at org.eclipse.core.internal.resources.Container.getFile(Container.java:167)
	at org.bndtools.build.api.AbstractBuildErrorDetailsHandler.getDefaultResource(AbstractBuildErrorDetailsHandler.java:67)
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:130)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:121)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 bndtools.builder 4 0 2015-03-10 17:43:31.867
!MESSAGE Build Error!
!STACK 0
java.lang.IllegalArgumentException: Path must include project and resource name: /foo.bar
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2137)
	at org.eclipse.core.internal.resources.Container.getFile(Container.java:167)
	at org.bndtools.build.api.AbstractBuildErrorDetailsHandler.getDefaultResource(AbstractBuildErrorDetailsHandler.java:67)
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:130)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:121)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY bndtools.builder 1 0 2015-03-10 17:43:31.875
!MESSAGE Unable to get workspace
!STACK 0
java.lang.IllegalArgumentException: No Workspace found from: C:\Users\sbright\jersey
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:154)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:107)
	at bndtools.central.Central.getWorkspace(Central.java:242)
	at org.bndtools.builder.CnfWatcher.resourceChanged(CnfWatcher.java:40)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:156)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.core.resources 4 75 2015-03-10 17:43:31.879
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 bndtools.builder 4 75 2015-03-10 17:43:31.879
!MESSAGE Errors running builder 'Bndtools Builder' on project 'foo.bar'.
!STACK 1
org.eclipse.core.runtime.CoreException: Build Error!
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:268)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalArgumentException: Path must include project and resource name: /foo.bar
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2137)
	at org.eclipse.core.internal.resources.Container.getFile(Container.java:167)
	at org.bndtools.build.api.AbstractBuildErrorDetailsHandler.getDefaultResource(AbstractBuildErrorDetailsHandler.java:67)
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:130)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:121)
	... 12 more
!SUBENTRY 2 bndtools.builder 4 0 2015-03-10 17:43:31.880
!MESSAGE Build Error!
!STACK 0
java.lang.IllegalArgumentException: Path must include project and resource name: /foo.bar
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2137)
	at org.eclipse.core.internal.resources.Container.getFile(Container.java:167)
	at org.bndtools.build.api.AbstractBuildErrorDetailsHandler.getDefaultResource(AbstractBuildErrorDetailsHandler.java:67)
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:130)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:121)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 bndtools.builder 4 0 2015-03-10 17:43:31.880
!MESSAGE Build Error!
!STACK 0
java.lang.IllegalArgumentException: Path must include project and resource name: /foo.bar
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2137)
	at org.eclipse.core.internal.resources.Container.getFile(Container.java:167)
	at org.bndtools.build.api.AbstractBuildErrorDetailsHandler.getDefaultResource(AbstractBuildErrorDetailsHandler.java:67)
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:130)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:121)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</pre>

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bndtools/pull/1071
