### ISSUE TITLE
Deadlock when building workspace

### ISSUE THREAD

**Issue by lukewink** [bndtools/bndtools#1105]
I'm seeing an issue where eclipse will hang when building the workspace.  A thread dump shows 2 threads deadlocked on each other:
```
Worker-18" prio=6 tid=0x000000001469d000 nid=0x1f9c waiting for monitor entry [0x000000001b7ee000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at aQute.bnd.build.Project.getBuilder(Project.java:133)
	- waiting to lock <0x0000000782c5cd28> (a aQute.bnd.build.Project)
	at aQute.bnd.build.Project.getSubBuilders(Project.java:2138)
	at aQute.bnd.build.Project.getVersions(Project.java:2706)
	- locked <0x0000000782cb0348> (a java.util.LinkedHashMap)
	at aQute.bnd.build.WorkspaceRepository.versions(WorkspaceRepository.java:131)
	at aQute.bnd.build.Project.getBundle(Project.java:979)
	at aQute.bnd.build.Project.getBundles(Project.java:506)
	at aQute.bnd.build.Project.parseBuildpath(Project.java:418)
	at aQute.bnd.build.Project.prepare(Project.java:274)
	- locked <0x000000078247fca0> (a aQute.bnd.build.Project)
	at aQute.bnd.build.Project.getBuildpath(Project.java:620)
	at org.bndtools.builder.classpath.BndContainerInitializer.calculateProjectClasspath(BndContainerInitializer.java:190)
	at org.bndtools.builder.classpath.BndContainerInitializer.resetClasspaths(BndContainerInitializer.java:111)
	at org.bndtools.builder.classpath.BndContainerInitializer.resetClasspaths(BndContainerInitializer.java:104)
	at org.bndtools.builder.jobs.newproject.AdjustClasspathsForNewProjectJob.runInWorkspace(AdjustClasspathsForNewProjectJob.java:53)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```
```
"Worker-13" prio=6 tid=0x0000000014699800 nid=0xe0c waiting for monitor entry [0x000000001b31e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at aQute.bnd.build.Project.getVersions(Project.java:2705)
	- waiting to lock <0x0000000782cb0348> (a java.util.LinkedHashMap)
	at aQute.bnd.build.WorkspaceRepository.versions(WorkspaceRepository.java:131)
	at aQute.bnd.build.Project.getBundle(Project.java:979)
	at aQute.bnd.build.Project.getBundles(Project.java:506)
	at aQute.bnd.build.Project.parseBuildpath(Project.java:418)
	at aQute.bnd.build.Project.prepare(Project.java:274)
	- locked <0x0000000782c5cd28> (a aQute.bnd.build.Project)
	at aQute.bnd.build.Project.getBuildpath(Project.java:620)
	at org.bndtools.builder.classpath.BndContainerInitializer.calculateProjectClasspath(BndContainerInitializer.java:190)
	at org.bndtools.builder.classpath.BndContainerInitializer.resetClasspaths(BndContainerInitializer.java:111)
	at org.bndtools.builder.classpath.BndContainerInitializer.resetClasspaths(BndContainerInitializer.java:104)
	at org.bndtools.builder.jobs.newproject.AdjustClasspathsForNewProjectJob.runInWorkspace(AdjustClasspathsForNewProjectJob.java:53)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

As you can see, the Project class sychronizes on itself, then when calling getVersions will attempt to sychronize on every other Project instance.  Since eclipse builds multiple projects simultaneously, this often causes a deadlock.

**Comment by bjhargrave** [comment]
This has been fixed for bndtools 3.0 by https://github.com/bndtools/bndtools/commit/4cc2030c8b268796fec57e6e0cbd8a9fbe74fc17. See also https://github.com/bndtools/bndtools/issues/944.
