### ISSUE TITLE
NPE Building wrapped bundle with Private-Package com.sun.jna

### ISSUE THREAD

**Issue by ro6** [bndtools/bndtools#1129]
I'm preparing a wrapped bundle for yajsw-11.11 following the instructions: https://github.com/bndtools/bndtools/wiki/How-to-Wrap-Bundles
Yajsw has several dependencies, including `com.sun.jna`, that I'm trying to include in the `Private-Package` header. All jars listed in the `-classpath` header come from the `lib` directory of the yajsw release available at: https://sourceforge.net/projects/yajsw/files/yajsw/yajsw-stable-11.11/yajsw-stable-11.11.zip/download
Building the bundle succeeds with the following bnd file:
```
Bundle-Version: 1.0.1.${build-version}
Export-Package: org.rzo.yajsw.*
Private-Package:  \
	com.karneim.*,\
	com.caucho.hessian4.*
Import-Package: \
	!groovy.*,\
	!com.jeta.*,\
	!com.jgoodies.*,\
	*
-classpath: \
	jar/yajsw-11.11/wrapper.jar,\
	jar/yajsw-11.11/wrapperApp.jar,\
	jar/yajsw-11.11/jna-3.4.1.jar,\
	jar/yajsw-11.11/platform-3.4.1.jar,\
	jar/yajsw-11.11/ahessian.jar,\
	jar/yajsw-11.11/hessian4.jar,\
	jar/yajsw-11.11/netty-3.6.6.Final.jar,\
	jar/yajsw-11.11/jrexx-1.1.1.jar
```
But fails as soon as I add `com.sun.jna` to the `Private-Package` section with this error:
```
org.eclipse.core.runtime.CoreException: Build Error!
	at org.bndtools.builder.NewBuilder.build(NewBuilder.java:203)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.NullPointerException
	at org.bndtools.builder.handlers.baseline.BaselineErrorHandler.generateAddedMethodMarker(BaselineErrorHandler.java:155)
	at org.bndtools.builder.handlers.baseline.BaselineErrorHandler.generateStructuralChangeMarkers(BaselineErrorHandler.java:129)
	at org.bndtools.builder.handlers.baseline.BaselineErrorHandler.generateMarkerData(BaselineErrorHandler.java:65)
	at org.bndtools.builder.NewBuilder.addBuildMarkers(NewBuilder.java:886)
	at org.bndtools.builder.NewBuilder.createBuildMarkers(NewBuilder.java:849)
	at org.bndtools.builder.NewBuilder.rebuild(NewBuilder.java:703)
	at org.bndtools.builder.NewBuilder.rebuildIfLocalChanges(NewBuilder.java:545)
	at org.bndtools.builder.NewBuilder.build(NewBuilder.java:179)
	... 12 more
```
Session data:
```
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

Created Time: 2015-06-30 11:00:18.608
```
Bndtools version: `2.4.1.REL-20150116-150145-g75d944b`
Java -version: `openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)`
OS: Arch Linux 4.0.6-1-ck x86_64

Where do I find the "bndtools jar files" mentioned at https://github.com/bndtools/bndtools/blob/master/CONTRIBUTING.md?

**Comment by pkriens** [comment]
Please test this on the latest build 3.0.0 since this code has been significantly changed
