### ISSUE TITLE
Can't Run from bnd.bnd file in 3.1.0 CI build

### ISSUE THREAD

**Issue by seanbright** [bndtools/bndtools#1190]
Hi,

With the latest CI build of Bndtools on Windows 10 with Java 1.8:

1. Select new empty eclipse workspace (directory name is bndtools-cannot-launch)
2. Create new project using Empty template (com.example.simple)
3. Create cnf project from Bundle-Hub template
4. Add osgi.core to build deps for com.example.simple
5. Create simple Activator and update bnd.bnd to reference it
6. Go to Run tab, bring in com.example.simple workspace bundle
7. Set framework and EE setting
8. Click Run

I get the following exception:

```
Status ERROR: bndtools.core code=0 Error initialising bnd launcher java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at aQute.bnd.build.Project.getHandler(Project.java:2436)
	at aQute.bnd.build.Project.getProjectLauncher(Project.java:2391)
	at bndtools.launch.OSGiRunLaunchDelegate.initialiseBndLauncher(OSGiRunLaunchDelegate.java:64)
	at bndtools.launch.AbstractOSGiLaunchDelegate.buildForLaunch(AbstractOSGiLaunchDelegate.java:53)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:855)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.FileNotFoundException: During copy: C:\Program Files\eclipse\bndtools-cannot-launch.jar
	at aQute.lib.io.IO.copy(IO.java:249)
	at aQute.bnd.build.Project.saveBuild(Project.java:1731)
	at aQute.bnd.build.Project.buildLocal(Project.java:1656)
	at aQute.bnd.build.Project.build(Project.java:1499)
	at aQute.bnd.build.Project.build(Project.java:1960)
	at aQute.bnd.build.ProjectLauncher.updateFromProject(ProjectLauncher.java:95)
	at aQute.bnd.build.ProjectLauncher.<init>(ProjectLauncher.java:70)
	at aQute.launcher.plugin.ProjectLauncherImpl.<init>(ProjectLauncherImpl.java:59)
	... 13 more
```

Replicating workspace is here:

https://github.com/seanbright/bndtools-cannot-launch

A couple things stand out to me:

1. It's trying to copy a jar named after the workspace directory and not the project
2. It's trying to copy it from or to the eclipse working directory

**Comment by bjhargrave** [comment]
This seems to have fixed my problem running Bnd OSGi Test Launcher (JUnit).

**Comment by seanbright** [comment]
Fix Confirmed. Thanks!
