### ISSUE TITLE
NPE with new project

### ISSUE THREAD

**Issue by djencks** [bndtools/bndtools#1199]
eclipse luna
  Bndtools	3.1.0.DEV-20151012-160359-g61a8cdd	bndtools.main.feature.feature.group	Bndtools
Trying to start from scratch with a new workspace.  Created new bndtools project test2. Made it an empty osgi project.  Put cnf next to test2. After closing the wizard got an error pop-up, the error log view shows an error and the detail shows:
{code}
An internal error occurred during: "Rebuilding bnd projects after creating workspace configuration.".
{code}
{code}
java.lang.NullPointerException
	at org.bndtools.builder.listeners.CnfSetupBuildListener$RebuildProjectsJob.runInWorkspace(CnfSetupBuildListener.java:76)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
{code}
This is preceded in the error log by 
{code}
Unable to get bnd project for project test2
{code}
{code}
java.lang.IllegalArgumentException: No Workspace found from: /Users/david/projects/felix/eclipse-bndtools-2
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:190)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:143)
	at bndtools.central.Central.getWorkspace(Central.java:280)
	at bndtools.central.Central.getProject(Central.java:583)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.<init>(BndContainerInitializer.java:181)
	at org.bndtools.builder.classpath.BndContainerInitializer.initialize(BndContainerInitializer.java:72)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:2902)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:1937)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3247)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.create(CPListElement.java:593)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.create(CPListElement.java:578)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.BuildPathsBlock.getCPListElements(BuildPathsBlock.java:423)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.BuildPathsBlock.init(BuildPathsBlock.java:327)
	at org.eclipse.jdt.ui.wizards.JavaCapabilityConfigurationPage.init(JavaCapabilityConfigurationPage.java:151)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo.initializeBuildPath(NewJavaProjectWizardPageTwo.java:318)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo.updateProject(NewJavaProjectWizardPageTwo.java:252)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo.access$2(NewJavaProjectWizardPageTwo.java:200)
	at org.eclipse.jdt.ui.wizards.NewJavaProjectWizardPageTwo$1UpdateRunnable.run(NewJavaProjectWizardPageTwo.java:161)
	at org.eclipse.ui.actions.WorkspaceModifyDelegatingOperation.execute(WorkspaceModifyDelegatingOperation.java:69)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:106)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:118)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
{code}

and three of these: (one with a longer stack trace)
{code}
Unable to get workspace
{code}
{code}
java.lang.IllegalArgumentException: No Workspace found from: /Users/david/projects/felix/eclipse-bndtools-2
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:190)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:143)
	at bndtools.central.Central.getWorkspace(Central.java:280)
	at org.bndtools.builder.CnfWatcher.resourceChanged(CnfWatcher.java:40)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:156)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
{code}

**Comment by bjhargrave** [comment]
The NPE is fixed by the commit. The 2 info logs are normal in a fresh workspace.
