### ISSUE TITLE
Updating a running framework fails with IndexOutOfBoundsException

### ISSUE THREAD

**Issue by brampouwelse** [bndtools/bndtools#1217]
Updating a running framework often fails with an IndexOutOfBoundsException, updating projects with no or little dependencies is fine most of the time but when updating a project has a lot of dependent projects I get exceptions like: 

```
! Error in updating the framework from the properties: Index: 0, Size: 0
! Bundle files does not exist: /Users/brampouwelse/git-repos/path/to/project/generated/***mybundle***.jar
ERROR: Bundle ***mybundle*** [251] Unable to update the bundle. (java.lang.IndexOutOfBoundsException: Index: 0, Size: 0)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.apache.felix.framework.BundleImpl.adapt(BundleImpl.java:1064)
	at org.apache.felix.framework.BundleImpl.getSymbolicName(BundleImpl.java:896)
	at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1226)
	at org.apache.felix.framework.BundleImpl.revise(BundleImpl.java:1141)
	at org.apache.felix.framework.Felix.updateBundle(Felix.java:2282)
	at org.apache.felix.framework.BundleImpl.update(BundleImpl.java:973)
	at org.apache.felix.framework.BundleImpl.update(BundleImpl.java:960)
	at aQute.launcher.Launcher.synchronizeFiles(Launcher.java:534)
	at aQute.launcher.Launcher.update(Launcher.java:405)
	at aQute.launcher.Launcher$1.run(Launcher.java:194)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
! Failed to update bundle /Users/brampouwelse/git-repos/path/to/project/generated/***mybundle***.jar, exception Update of bundle ***mybundle*** [251] failed.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.apache.felix.framework.BundleImpl.adapt(BundleImpl.java:1064)
ERROR: Bundle ***myotherbundle*** [252] Unable to update the bundle. (java.lang.IndexOutOfBoundsException: Index: 0, Size: 0)
	at org.apache.felix.framework.BundleImpl.getSymbolicName(BundleImpl.java:896)
	at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1226)
	at org.apache.felix.framework.BundleImpl.revise(BundleImpl.java:1141)
	at org.apache.felix.framework.Felix.updateBundle(Felix.java:2282)
	at org.apache.felix.framework.BundleImpl.update(BundleImpl.java:973)
	at org.apache.felix.framework.BundleImpl.update(BundleImpl.java:960)
	at aQute.launcher.Launcher.synchronizeFiles(Launcher.java:534)
	at aQute.launcher.Launcher.update(Launcher.java:405)
	at aQute.launcher.Launcher$1.run(Launcher.java:194)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
! Failed to update bundle /Users/brampouwelse/git-repos/path/to/project/generated/***myotherbundle***.jar, exception Update of bundle ***myotherbundle*** [252] failed.
```

**Comment by bjhargrave** [comment]
I would suggest that this is an error in Apache Felix and not bnd. Calling Bundle.update should never result in such an exception. I am guessing Felix does not like the `***`s in your bundle names.

**Comment by brampouwelse** [comment]
My bundles are not actually called ***mybundle*** and ***myotherbundle*** they are also not in a folder named "path/to/project/" but I've anonymized the names ...

**Comment by bjhargrave** [comment]
Well, in any case, it appears to be a bug in Apache Felix. No input to Bundle.update should result in such a runtime exception.

**Comment by brampouwelse** [comment]
Created: https://issues.apache.org/jira/browse/FELIX-5103
