### ISSUE TITLE
3.1.0.REL: deadlock in the builder

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1259]
I'm experiencing the builder deadlock (or at least appear to hang) very often on my bndtoolsPlugins project.

Especially when switching branches outside out Eclipse.
Rather serious and annoying since I have to `killall java` to close Eclipse, it will not even shutdown properly.

**Comment by fhuberts** [comment]
This is very serious:
I had disabled automatic builds, then did a 'clean all projects' and it hung.
It can't even clean.

**Comment by bjhargrave** [comment]
Perhaps you can give some actual, useful details such as an example project having this problem and instructions on how to reproduce so that someone can investigate?

**Comment by fhuberts** [comment]
actual project: "my bndtoolsPlugins project"
useful details: "Especially when switching branches outside out Eclipse" and "I had disabled automatic builds, then did a 'clean all projects' and it hung"

Please enlighten me how I can be more specific.

A deadlock (or a seeming one) is rather hard to describe.
Also, it isn't 100% reproducible, but I have it a lot.

For kicks I'll throw in the project link: https://github.com/fhuberts/bndtoolsPlugins

**Comment by fhuberts** [comment]
Clone the project, open eclipse on it, with automatic building.
Now switch between the release-3.1 branch and master outside of Eclipse.

This is how I (somewhat) easily triggered it

Fedora 23 x64
openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)

Eclipse Mars SR1

**Comment by bjhargrave** [comment]
I have found switching branches, with significant differences such as projects coming and going, under Eclipse to be an exercise in masochism. I don't do it. I just use separate git workspaces and eclipse workspaces for the different branches.

**Comment by fhuberts** [comment]
Agree, but it didn't deadlock or hang. Now it does.

**Comment by bjhargrave** [comment]
The diff between your branches completely changes the repo contents. It would be better to stop eclipse between branch switches in that case.

I agree this problem needs some attention. But it is not super critical since you can work around.

**Comment by fhuberts** [comment]
I did stop auto-building as a test, didn't matter.

I dug up more info:

AFAICT this commit was still ok:

Git-Descriptor: 3.0.0.REL-98-gfc3bcfe
Git-SHA: fc3bcfe4579a3eb062f6ac3744a0385c52ac186f

**Comment by bjhargrave** [comment]
I don't think the builder is the issue. It is the repo switching. Your branches change the URLs of the repos and thus there content. Reacting to this is where things go south. Bndtools was changed in RC3 to do repo actions in a job. See https://github.com/bndtools/bndtools/commit/524b99b1ce43ae6a06fe098b4ea24298bdd726e0. You may want to try [3.1.0.RC2](https://bndtools.ci.cloudbees.com/job/bndtools.master/1713/artifact/build/generated/p2/) so see if the problem is abated.

**Comment by fhuberts** [comment]
Well, how about reverting that change until it works properly?

I had it hang on me too when I did a clean _without_ changing branches...
How's that for 'buggy" ?

**Comment by BryanHunt** [comment]
Not sure if this is the same bug, but I'm seeing a deadlock as well when I update a bundle repository and then make a change to the build.bnd because the repo location changed.


Found one Java-level deadlock:
=============================
"Worker-16":
  waiting to lock monitor 0x000000012c99fca8 (object 0x000000078495a980, a java.util.LinkedHashMap),
  which is held by "Worker-12"
"Worker-12":
  waiting to lock monitor 0x000000012c9a30e8 (object 0x0000000784950ca0, a aQute.bnd.build.Project),
  which is held by "Worker-16"

Java stack information for the threads listed above:
===================================================
"Worker-16":
	at aQute.bnd.build.Project.getVersions(Project.java:2780)
	- waiting to lock <0x000000078495a980> (a java.util.LinkedHashMap)
	at aQute.bnd.build.WorkspaceRepository.versions(WorkspaceRepository.java:143)
	at aQute.bnd.build.Project.getBundle(Project.java:1137)
	at aQute.bnd.build.Project.getBundles(Project.java:597)
	at aQute.bnd.build.Project.parseBuildpath(Project.java:508)
	at aQute.bnd.build.Project.prepare(Project.java:363)
	- locked <0x0000000784950ca0> (a aQute.bnd.build.Project)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
"Worker-12":
	at aQute.bnd.build.Project.getBuilder(Project.java:199)
	- waiting to lock <0x0000000784950ca0> (a aQute.bnd.build.Project)
	at aQute.bnd.build.Project.getSubBuilders(Project.java:2370)
	at aQute.bnd.build.Project.getVersions(Project.java:2782)
	- locked <0x000000078495a980> (a java.util.LinkedHashMap)
	at aQute.bnd.build.Project.getBsns(Project.java:2801)
	at aQute.bnd.build.WorkspaceRepository.list(WorkspaceRepository.java:119)
	at bndtools.central.RepositoriesViewRefresher.ensureLoaded(RepositoriesViewRefresher.java:130)
	at bndtools.central.RepositoriesViewRefresher.access$100(RepositoriesViewRefresher.java:29)
	at bndtools.central.RepositoriesViewRefresher$1.runInWorkspace(RepositoriesViewRefresher.java:78)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by fhuberts** [comment]
Ok, so there are multiple users experiencing a **DEADLOCK**.

A deadlock is a regression of the most serious kind and resulting in a 'rather' poor user experience.

How about tracing what caused it, reverting that and issuing 3.1.1.REL?

**Comment by bjhargrave** [comment]
Thanks @BryanHunt for the very useful information. I know see what the issue is. It was introduced in https://github.com/bndtools/bndtools/commit/7ac22368a280744aa4637e2bc824a231c4e0d8c2. The problem is that the bndlib code is not thread safe so bndtools must hold a lock before calling it to do anything non-trivial. https://github.com/bndtools/bndtools/blob/master/bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java#L130 is non-trivial. So we need to add locking in here. I'll work on a fix.

**Comment by bjhargrave** [comment]
I have made a test 3.1.1.DEV build at https://bndtools.ci.cloudbees.com/job/bndtools.next/lastSuccessfulBuild/artifact/build/generated/p2/ with the above fix. Please try it out.
