### ISSUE TITLE
UnsupportedOperationException during resolve

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#1289]
Resolve a bndrun containing a requirement for bundle `org.apache.aries.blueprint`. The resolution fails with `java.lang.UnsupportedOperationException`. No stack trace or other details -- only the exception name appears in the Results dialog.

This is a regresion in 3.2, as it works in 3.1.1.

**Comment by njbartlett** [comment]
Debugging reveals the following stack trace:

	org.osgi.service.resolver.ResolutionException: java.lang.UnsupportedOperationException
		at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:55)
		at org.bndtools.core.resolve.ResolveOperation.run(ResolveOperation.java:65)
		at org.bndtools.core.resolve.ResolveJob.run(ResolveJob.java:57)
		at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
	Caused by: java.lang.UnsupportedOperationException
		at org.apache.felix.resolver.util.CopyOnWriteList.add(CopyOnWriteList.java:135)
		at biz.aQute.resolve.AbstractResolveContext.insertHostedCapability(AbstractResolveContext.java:167)
		at org.apache.felix.resolver.Candidates.prepare(Candidates.java:934)
		at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:232)
		at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:158)
		at biz.aQute.resolve.BndResolver.resolve(BndResolver.java:22)
		at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:68)
		at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:52)
		... 3 more

**Comment by bjhargrave** [comment]
Resolver was recently updated to 1.8 so this may be due to that: https://github.com/bndtools/bnd/pull/1184
