### ISSUE TITLE
A baseline error not reported in Eclipse

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1310]
I had a project where I removed a method. This first caused an error on the source & the packageinfo. This was fixed going to the next MAJOR version but then the project failed to generate a JAR without giving an error. 

Gradle then showed there was a baseline error on the bundle. 
It therefore seems that the baseline error on the bundle is not reported.

**Comment by pkriens** [comment]
java.lang.NullPointerException
	at org.bndtools.builder.handlers.baseline.BaselineErrorHandler.generatePackageInfoMarkers(BaselineErrorHandler.java:114)
	at org.bndtools.builder.handlers.baseline.BaselineErrorHandler.generateMarkerData(BaselineErrorHandler.java:81)
	at org.bndtools.build.api.AbstractBuildErrorDetailsHandler.generateMarkerData(AbstractBuildErrorDetailsHandler.java:365)
	at org.bndtools.builder.MarkerSupport.createMarker(MarkerSupport.java:88)
	at org.bndtools.builder.MarkerSupport.createMarkers(MarkerSupport.java:78)
	at org.bndtools.builder.MarkerSupport.setMarkers(MarkerSupport.java:61)
	at org.bndtools.builder.BndtoolsBuilder.report(BndtoolsBuilder.java:309)
	at org.bndtools.builder.BndtoolsBuilder.access$1100(BndtoolsBuilder.java:68)
	at org.bndtools.builder.BndtoolsBuilder$1.call(BndtoolsBuilder.java:288)
	at org.bndtools.builder.BndtoolsBuilder$1.call(BndtoolsBuilder.java:138)
	at bndtools.central.Central.bndCall(Central.java:595)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:138)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by pkriens** [comment]
d6b6e2108104538281253f75a0af5c386008251b seems to assume there is a package-info.java
