### ISSUE TITLE
slf4j linkage error in Eclipse

### ISSUE THREAD

**Issue by psoreide** [bndtools/bndtools#1371]
I get the following during startup of Eclipse Mars.2. Still investigating, but maybe a showstopper. 

java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:385)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:328)
	at aQute.bnd.osgi.Processor.<init>(Processor.java:97)
	at aQute.bnd.build.Workspace.getDefaults(Workspace.java:145)
	at aQute.bnd.build.Workspace.<init>(Workspace.java:216)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:204)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:151)
	at bndtools.central.Central.getWorkspace(Central.java:210)
	at bndtools.central.Central.getProject(Central.java:517)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.<init>(BndContainerInitializer.java:180)
	at org.bndtools.builder.classpath.BndContainerInitializer.initialize(BndContainerInitializer.java:71)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:2868)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:1900)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3298)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2693)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2857)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:1962)
	at org.eclipse.jdt.internal.core.JavaProject.computeExpandedClasspath(JavaProject.java:509)
	at org.eclipse.jdt.internal.core.JavaProject.getExpandedClasspath(JavaProject.java:1567)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.computeClasspathLocations(NameEnvironment.java:100)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.<init>(NameEnvironment.java:48)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:604)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:169)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by bjhargrave** [comment]
How many slf4j bundles/packages are in your eclipse installation?

**Comment by psoreide** [comment]
Eclipse itself provides org.sfl4j.api and org.slf4j.impl.log4j12 1.7.2. Looks like this is from the jgit feature (4.1.1).

Then we have slf4j.api and slf4j.simple 1.7.18 which is from bndtools.

**Comment by bjhargrave** [comment]
I don't install jgit, so my eclipse installation has no sl4fj other than what bndtools installs. So how do we handle this?

**Comment by psoreide** [comment]
If egit is not dependent on jgit I'll just remove it. But this is probably not a solution for everyone.

**Comment by bjhargrave** [comment]
egit does depend upon jgit. I would like to know the proper way for an eclipse feature to depend upon sl4fj.

**Comment by bjhargrave** [comment]
@psoreide Try the latest build from cloudbees.

**Comment by psoreide** [comment]
LGTM
