### ISSUE TITLE
"Resource has no content" Exception when pressing "Finish" on resolve window

### ISSUE THREAD

**Issue by tomq42** [bndtools/bndtools#1403]
So I have a problem where having pressed "Resolve" and then trying to press finish, nothing happens. Looking in the .metadata/.log file I see:

java.lang.IllegalArgumentException: Resource has no content
    at org.bndtools.utils.resources.ResourceUtils.getContentCapability(ResourceUtils.java:108)
    at org.bndtools.core.resolve.ui.ResolutionWizard.performFinish(ResolutionWizard.java:111)
    at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:799)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:429)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
    at org.eclipse.jface.window.Window.open(Window.java:803)
    at bndtools.editor.project.RunRequirementsPart$8.run(RunRequirementsPart.java:343)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

I don't actually know what bundle this is caused by. I had originally thought it was caused by org.h2, in that I could fairly reliably make it go away and come back by adding and removing that bundle, but now I get it all the time, regardless.
It would be nice at the least to have some report of what bundle was being resolved at the time so I can try and further diagnose.

**Comment by tomq42** [comment]
This is incredibly frustrating. 

I've been playing with this for a few hours now, adding and removing things from my bndrun file to try and work out the culprit, but it's very inconsistent.

My bndrun file now consists of:

-runrequires: \
	osgi.identity;filter:='(osgi.identity=org.apache.felix.gogo.runtime)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.gogo.shell)',\
	osgi.identity;filter:='(osgi.identity=org.amdatu.web.rest.doc)',\
	osgi.identity;filter:='(osgi.identity=org.amdatu.web.rest.doc.swagger)',\
	osgi.identity;filter:='(osgi.identity=org.amdatu.web.rest.doc.swagger.ui)',\
	osgi.identity;filter:='(osgi.identity=org.amdatu.web.rest.wink)'


-runbundles: \
	com.wpl.woodpecker.provider;version=snapshot,\
	org.apache.felix.configadmin;version='[1.8.6,1.8.7)',\
	org.apache.felix.gogo.runtime;version='[0.16.2,0.16.3)',\
	org.apache.felix.gogo.shell;version='[0.10.0,0.10.1)',\
	org.apache.felix.log;version='[1.0.1,1.0.2)',\
	org.apache.felix.scr;version='[2.0.0,2.0.1)',\
	org.eclipse.equinox.metatype;version='[1.4.100,1.4.101)',\
	org.osgi.service.metatype;version='[1.3.0,1.3.1)'
-runproperties: org.osgi.framework.bootdelegation='sun.*,com.sun.*'

So I have none of my own bundles at all! Duplicate this into a fresh workspace and it works just fine.

**Comment by tomq42** [comment]
OK. Finally tracked this down to a local repository I had.
Removed the repository and the problem goes away.
The index.xml file is all full of errors. See attachment.
[index.zip](https://github.com/bndtools/bndtools/files/320457/index.zip)

**Comment by gamerson** [comment]
@tomq42 do you have an example repository or a way I can reproduce this original error so I can attempt a fix?  thanks

**Comment by gamerson** [comment]
hey @tomq42 just pinging here on this, to see if you have an easy way for me to reproduce so that I can try a fix.

**Comment by tomq42** [comment]
Well in the first instance, as I mentioned in the original issue, there's nothing to tell me what bundle was giving the problem, so that would be something that would be useful to fix.
I done know what the reproduction steps are, as I say, the culprit was the attached index file. I didn't investigate the contents of the index, beyond my level of understanding.

**Comment by Katsuya-Tomioka** [comment]
Just to note my experience since I was getting the exact same problem. For my case, it was bundles in our company's private maven repo which were failed to download from Maven central. After fixing BndPomRepository's releaseUrl in cnf, (and successfully downloading all remaining bundles) I got a successful resolve. But there was no clue other than "eclipse error reporting" popup saying mysterious "Resource has no content".

**Comment by bjhargrave** [comment]
Closing as an old issue.
