### ISSUE TITLE
New workspace startup in Neon popup dialog error because of missing repos

### ISSUE THREAD

**Issue by gamerson** [bndtools/bndtools#1424]
The new ProgressUI code doesn't gracefully handle the situation when a new Neon workspace startup doesn't have any repo/workspace content and it throws a couple of errors.

**Comment by gamerson** [comment]
<img width="388" alt="screen shot 2016-06-28 at 9 48 41 am" src="https://cloud.githubusercontent.com/assets/595221/16420141/d81f049c-3d15-11e6-8b52-a549bf13d7b5.png">

```
java.lang.IllegalArgumentException: No Workspace found from: /Users/greg/dev/sdks/neon_jee/workspace
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:197)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:151)
	at bndtools.central.Central.getWorkspace(Central.java:211)
	at bndtools.central.Central.getWorkspaceBuildFile(Central.java:162)
	at bndtools.OpenExtConfigsContributionItem.getContributionItems(OpenExtConfigsContributionItem.java:37)
	at org.eclipse.ui.actions.CompoundContributionItem.getContributionItemsToFill(CompoundContributionItem.java:86)
	at org.eclipse.ui.actions.CompoundContributionItem.fill(CompoundContributionItem.java:59)
	at org.eclipse.ui.internal.menus.DynamicMenuContributionItem.fill(DynamicMenuContributionItem.java:147)
	at org.eclipse.jface.action.MenuManager.doItemFill(MenuManager.java:728)

```
```
java.lang.IllegalArgumentException: No Workspace found from: /Users/greg/dev/sdks/neon_jee/workspace
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:197)
	at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:151)
	at bndtools.central.Central.getWorkspace(Central.java:211)
	at bndtools.central.Central.refreshPlugins(Central.java:440)
	at bndtools.views.repository.RepositoriesView$8$1.runInWorkspace(RepositoriesView.java:492)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
```
