### ISSUE TITLE
gradle build fails to resolve dependencies

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1468]
I have a workspace that contains only one bundle that is an integration test.  If you start with an empty ~/.bnd directory, the project will fail to resolve bundles on the check task with errors like:

```
java.io.IOException: Could not open URL, [404] Not Found for 'http://www.mirrorservice.org/sites/ftp.apache.org//felix/org.apache.felix.configadmin-1.8.8.jar'
	at aQute.bnd.jpm.StoredRevisionCache.getConnection(StoredRevisionCache.java:201)
	at aQute.bnd.jpm.StoredRevisionCache.doDownload(StoredRevisionCache.java:144)
	at aQute.bnd.jpm.StoredRevisionCache.download(StoredRevisionCache.java:104)
	at aQute.bnd.jpm.Repository$1.run(Repository.java:343)
java.io.IOException: Could not open URL, [404] Not Found for 'http://www.mirrorservice.org/sites/ftp.apache.org//felix/org.apache.felix.webconsole-4.2.14-all.jar'
	at aQute.bnd.jpm.StoredRevisionCache.getConnection(StoredRevisionCache.java:201)
	at aQute.bnd.jpm.StoredRevisionCache.doDownload(StoredRevisionCache.java:144)
	at aQute.bnd.jpm.StoredRevisionCache.download(StoredRevisionCache.java:104)
	at aQute.bnd.jpm.Repository$1.run(Repository.java:343)
java.io.IOException: Could not open URL, [404] Not Found for 'http://www.mirrorservice.org/sites/ftp.apache.org//felix/org.apache.felix.http.jetty-3.1.6.jar'
	at aQute.bnd.jpm.StoredRevisionCache.getConnection(StoredRevisionCache.java:201)
	at aQute.bnd.jpm.StoredRevisionCache.doDownload(StoredRevisionCache.java:144)
	at aQute.bnd.jpm.StoredRevisionCache.download(StoredRevisionCache.java:104)
	at aQute.bnd.jpm.Repository$1.run(Repository.java:343)
```

This causes Jenkins pipeline builds to fail.

**Comment by bjhargrave** [comment]
I think we will need more information to debug. 
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by bjhargrave** [comment]
Also, this bug should be in the bnd repo rather than the bndtools repo.

**Comment by BryanHunt** [comment]
Moved to https://github.com/bndtools/bnd/issues/1594
