### ISSUE TITLE
Creating new Bnd OSGi Workspace doesn't initialize properly

### ISSUE THREAD

**Issue by seanbright** [bndtools/bndtools#1480]
**System Info:**

- Windows 10
- Java 1.8.0_101
- Eclipse Neon
- Bndtools 3.3.0.DEV (latest)

**Steps to reproduce:**

1. Open Eclipse, creating a new Eclipse Workspace
2. Switch to the Bndtools perspective, create a new Bnd OSGi Workspace (osgi/workspace)

**Observed behavior:**

The `cnf` directory appears, but the 'Repositories' view continues to display "Repositories are loading, please wait..." Opening `build.bnd` shows a hyperlink that says "Workspace is loading, please wait..." Clicking on the hyperlink throws an exception (see bottom of report).

After restarting Eclipse (via the 'Restart' menu item) the Workspace repository appears in the 'Repositories' view, but the other repositories do not. If you manually edit the `build.bnd` file and save it, the other repositories appear.

If you do not switch to the Bndtools perspective before creating the Bnd OSGi Workspace, Bndtools will prompt you to switch and when you do, you will see the Workspace repository but none of the others. To get them to appear you have to manually edit and save the `build.bnd` file.

**Additional Information**

Running or debugging Bndtools through Eclipse results in this sometimes working correctly and sometimes not, leading me to believe there are some subtle timing issues involved.

**Exception from "Workspace is loading" hyperlink**
<pre>
java.lang.NullPointerException
	at bndtools.utils.MessagesPopupDialog.createDialogArea(MessagesPopupDialog.java:72)
	at org.eclipse.jface.dialogs.PopupDialog.createContents(PopupDialog.java:694)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.PopupDialog.open(PopupDialog.java:1134)
	at bndtools.utils.MessageHyperlinkAdapter.showPopup(MessageHyperlinkAdapter.java:44)
	at bndtools.utils.MessageHyperlinkAdapter.linkActivated(MessageHyperlinkAdapter.java:30)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:228)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:322)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.access$2(AbstractHyperlink.java:306)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink$4.handleEvent(AbstractHyperlink.java:129)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
</pre>

**Comment by BryanHunt** [comment]
I've seen this exact same problem.

**Comment by seanbright** [comment]
I have a feeling that this will be helped by https://github.com/bndtools/bndtools/pull/1486
