### ISSUE TITLE
[3.3.0 RC2] Workspace-Init fails when run-file-editor was active on shutdown

### ISSUE THREAD

**Issue by lostiniceland** [bndtools/bndtools#1528]
Keeping a run-file as the active editor when closing Eclipse, the next startup will throw the following exception

`org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:373)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:631)
	at org.eclipse.ui.internal.forms.widgets.TitleRegion.updateImage(TitleRegion.java:362)
	at org.eclipse.ui.internal.forms.widgets.FormHeading.setImage(FormHeading.java:719)
	at org.eclipse.ui.forms.widgets.Form.setImage(Form.java:306)
	at org.eclipse.ui.forms.widgets.ScrolledForm.setImage(ScrolledForm.java:173)
	at bndtools.editor.pages.ProjectRunPage.updateFormImage(ProjectRunPage.java:238)
	at bndtools.editor.pages.ProjectRunPage.access$000(ProjectRunPage.java:43)
	at bndtools.editor.pages.ProjectRunPage$4.propertyChange(ProjectRunPage.java:216)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at aQute.bnd.build.model.BndEditModel.setWorkspace(BndEditModel.java:1098)
	at bndtools.editor.BndEditor.loadEditModel(BndEditor.java:492)
	at bndtools.editor.BndEditor.access$300(BndEditor.java:97)
	at bndtools.editor.BndEditor$3.call(BndEditor.java:474)
	at org.osgi.util.promise.PromiseImpl$Then.run(PromiseImpl.java:240)
	at org.osgi.util.promise.PromiseImpl.notifyCallbacks(PromiseImpl.java:137)
	at org.osgi.util.promise.PromiseImpl.resolve(PromiseImpl.java:119)
	at org.osgi.util.promise.Deferred.resolve(Deferred.java:80)
	at bndtools.central.Central.getWorkspace(Central.java:255)
	at bndtools.central.Central.refreshPlugins(Central.java:463)
	at bndtools.views.repository.RepositoriesView$8.runInWorkspace(RepositoriesView.java:432)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
`

The Run-Editor is not loading any data besides repository-information (see screenshot). Editor must be closed and opened again. 

![workspace-init-fail](https://cloud.githubusercontent.com/assets/1516116/18350543/b1045ade-75d6-11e6-94d1-73780c8bbc01.jpg)

The editor must wait for the workspace-init to complete before accessing any workspace information.

**Comment by seanbright** [comment]
@lostiniceland, can you try to replicate with RC2?

**Comment by lostiniceland** [comment]
@seanbright same behavior in RC2. I've updated the title

**Comment by seanbright** [comment]
@lostiniceland, confirmed in master as well. I've opened a PR.

**Comment by lostiniceland** [comment]
Confirming as fixed with latest DEV-build
