### ISSUE TITLE
Import existing bndtools project causes Eclipse Neon to freeze.

### ISSUE THREAD

**Issue by axiopisty** [bndtools/bndtools#1539]
# Steps to reproduce:

1. Clone https://github.com/timothyjward/osgi.enroute.examples.jdbc. 

2. Open Eclipse Neon. When it requires you to specify a workspace use `<~>/workspace/osgi.enroute.examples.jdbc` This should give you an empty workspace and eclipse should show you the welcome screen. Close the welcome screen and switch to the bndtools perspective. Right click in the package explorer. When the context menu appears select import. With the import wizard select >General>Existing Projects into Workspace, then next. Then Select the root directory to the root directory of the project you cloned in step 1. Click the Finish button.

3. Observe that the Import wizard freezes. The progress bar is stuck. The text says: "Opening 'osgi.enroute.examples.jdbc.addressbook.testdata.provider'." There is a red square button that indicates the task can be cancelled. Click it. The button will grey out, but the IDE is frozen.

4. Use the terminal to "$ pkill -f eclipse".

# Environment:

## ~/.p2/pool/plugins/bndtools.core_3.2.0.201605172024.jar:
Git-Descriptor: 3.2.0.REL
Git-SHA: 3a83c3304175296742123ce9cce632e584230da1
Bundle-Name: bndtools.core
Bundle-SCM: url=https://github.com/bndtools/bndtools, connection=scm:g
 it:https://github.com/bndtools/bndtools.git, developerConnection=scm:
 git:git@github.com:bndtools/bndtools.git
Bundle-SymbolicName: bndtools.core;singleton:=true

## $ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

## $ cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
cat: /etc/upstream-release: Is a directory

> Note: I've also reproduced this using OSX

## $cat ~/workspace/osgi.enroute.examples.jdbc/.metadata/.log
!SESSION 2016-09-10 08:22:46.133 -----------------------------------------------
eclipse.buildId=4.6.0.I20160606-1100
java.version=1.8.0_65
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.core.resources 2 10035 2016-09-10 08:24:22.820
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY bndtools.core 4 0 2016-09-10 08:24:28.503
!MESSAGE Unable to find default config files
!STACK 0
java.lang.IllegalArgumentException: No Workspace found from: /home/`<user>`/workspace/osgi.enroute.examples.jdbc
  at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:197)
  at aQute.bnd.build.Workspace.getWorkspace(Workspace.java:151)
  at bndtools.central.Central.getWorkspace(Central.java:210)
  at bndtools.central.Central.getWorkspaceBuildFile(Central.java:162)
  at bndtools.OpenExtConfigsContributionItem.getContributionItems(OpenExtConfigsContributionItem.java:37)
  at org.eclipse.ui.actions.CompoundContributionItem.getContributionItemsToFill(CompoundContributionItem.java:86)
  at org.eclipse.ui.actions.CompoundContributionItem.fill(CompoundContributionItem.java:59)
  at org.eclipse.ui.internal.menus.DynamicMenuContributionItem.fill(DynamicMenuContributionItem.java:147)
  at org.eclipse.jface.action.MenuManager.doItemFill(MenuManager.java:728)
  at org.eclipse.jface.action.MenuManager.update(MenuManager.java:810)
  at org.eclipse.jface.action.MenuManager.update(MenuManager.java:669)
  at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.scheduleManagerUpdate(MenuManagerRenderer.java:1185)
  at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.access$3(MenuManagerRenderer.java:1180)
  at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer$3.handleEvent(MenuManagerRenderer.java:247)
  at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
  at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
  at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
  at org.eclipse.swt.widgets.Display.syncExec(Display.java:5406)
  at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
  at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
  at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
  at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
  at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
  at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
  at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
  at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
  at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
  at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
  at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:94)
  at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
  at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
  at org.eclipse.e4.ui.model.application.ui.impl.UIElementImpl.setVisible(UIElementImpl.java:345)
  at org.eclipse.e4.ui.workbench.renderers.swt.ContributionRecord.updateVisibility(ContributionRecord.java:110)
  at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRendererFilter.updateElementVisibility(MenuManagerRendererFilter.java:189)
  at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRendererFilter.updateElementVisibility(MenuManagerRendererFilter.java:200)
  at org.eclipse.ui.internal.WorkbenchWindow$8.run(WorkbenchWindow.java:704)
  at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
  at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
  at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4528)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4146)
  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
  at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
  at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
  at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
  at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
  at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
  at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
  at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
  at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

!ENTRY bndtools.core 4 0 2016-09-10 08:24:50.594
!MESSAGE Error stopping startup participant
!STACK 0
java.lang.NullPointerException
  at bndtools.central.Central.stop(Central.java:119)
  at bndtools.Plugin.stopStartupParticipants(Plugin.java:141)
  at bndtools.Plugin.stop(Plugin.java:155)
  at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:830)
  at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
  at java.security.AccessController.doPrivileged(Native Method)
  at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:823)
  at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:946)
  at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:314)
  at org.eclipse.osgi.container.Module.doStop(Module.java:636)
  at org.eclipse.osgi.container.Module.stop(Module.java:498)
  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1661)
  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1580)
  at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:253)
  at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:147)
  at org.eclipse.osgi.container.Module.doStop(Module.java:636)
  at org.eclipse.osgi.container.Module.stop(Module.java:498)
  at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:191)
  at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
  at java.lang.Thread.run(Thread.java:745)

**Comment by seanbright** [comment]
Can you try with 3.3RC2?

>

**Comment by axiopisty** [comment]
Yes, I'll try that. But Eclipse is foreign to me. I normally use IntelliJ. Could you please explain how I install that version? My only experience with Eclipse is what I have done with the osgi enroute tutorial. Is there a way for me to get that version through the eclipse marketplace?

**Comment by rotty3000** [comment]
If you follow the installations instructions for bndtools again from
enRoute, but use the following url, it should work:

https://bndtools.ci.cloudbees.com/job/bndtools.next/84/artifact/build/generated/p2/

HTH

**Comment by axiopisty** [comment]
That worked! Thank you. Was this previously reported and fixed, or did you just fix this based on this issue?

Also, what is bndtools release schedule, when will v3.3RC2 be the default in the market place?

**Comment by rotty3000** [comment]
On Sat, Sep 10, 2016 at 1:00 PM, Elliot Huntington <notifications@github.com
> wrote:

> Was this previously reported and fixed, or did you just fix this based on
> this issue?
>
I think this is simply that there was a pretty significant amount of work
done on workspace initialization and it was best to check that first.

> Also, what is bndtools release schedule, when will v3.3RC2 be the default
> in the market place?
>
I would imagine that in roughly the next couple of weeks the final release
will be made. At that time it will appear in the marketplace as the full
fledged v3.3.
