### ISSUE TITLE
BndPomRepository, a feature request and a couple of errors

### ISSUE THREAD

**Issue by ivoleitao** [bndtools/bndtools#1571]
As mentioned in the bndtools mailing list namely in the topic https://groups.google.com/forum/#!topic/bndtools-users/rjcHE8kF-Po and originally discussed with @pkriens and @cschneider  I'm having a problems with the BndPomRepository plugin in my setup. 

Before presenting the errors, an improvement. I think it's important to configure in the plugin the ability to ignore transitive dependencies. I've noticed a lot of errors in the eclipse log file related with that dependencies. Despite the plugin working in that cases I think it would useful to have an option to disable transitive dependency checking since all the dependencies listed in my pom are all I need to run my app.
The problem now is two dependencies that were not successfully parsed:
First an apache cxf dependency:

```
<dependency>
    <groupId>org.apache.cxf</groupId>
    <artifactId>cxf-rt-rs-extension-providers</artifactId>
    <version>3.1.6</version>
</dependency>
```

which gives the following error:

```
!ENTRY org.eclipse.m2e.logback.appender 4 0 2016-10-30 18:48:02.443
!MESSAGE Failed to parse pom org.apache.cxf:cxf-rt-rs-extension-providers:3.1.6 from file /home/ivoleitao/.m2/repository/org/apache/cxf/cxf-rt-rs-extension-providers/3.1.6/cxf-rt-rs-extension-providers-3.1.6.pom
!STACK 0
java.lang.NullPointerException
    at aQute.lib.io.IO.getFile(IO.java:397)
    at aQute.lib.io.IO.getFile(IO.java:367)
    at aQute.maven.provider.POM.<init>(POM.java:145)
    at aQute.maven.provider.POM.<init>(POM.java:76)
    at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:309)
    at aQute.maven.provider.MavenRepository$2.apply(MavenRepository.java:338)
    at aQute.maven.provider.MavenRepository$2.apply(MavenRepository.java:331)
    at org.osgi.util.promise.PromiseImpl$Map.call(PromiseImpl.java:409)
    at org.osgi.util.promise.PromiseImpl$Then.run(PromiseImpl.java:240)
    at org.osgi.util.promise.PromiseImpl.notifyCallbacks(PromiseImpl.java:137)
    at org.osgi.util.promise.PromiseImpl.onResolve(PromiseImpl.java:175)
    at org.osgi.util.promise.PromiseImpl.then(PromiseImpl.java:184)
    at org.osgi.util.promise.PromiseImpl.then(PromiseImpl.java:192)
    at org.osgi.util.promise.PromiseImpl.map(PromiseImpl.java:393)
    at aQute.maven.provider.MavenRepository.getPomPromise(MavenRepository.java:331)
    at aQute.maven.provider.MavenRepository.getPom(MavenRepository.java:317)
    at aQute.bnd.repository.maven.pom.provider.Traverser.parseArchive(Traverser.java:167)
    at aQute.bnd.repository.maven.pom.provider.Traverser.access$000(Traverser.java:40)
    at aQute.bnd.repository.maven.pom.provider.Traverser$1.run(Traverser.java:132)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Then I have a problem with the following dependency:

```
<dependency>
    <groupId>org.apache.aries.rsa.discovery</groupId>
    <artifactId>org.apache.aries.rsa.discovery.zookeeper</artifactId>
    <version>${lib.org.apache.aries.rsa.discovery.zookeeper.version}</version>
</dependency>
```

For which I have not found any exception in the log. 

I think BndPomRepository is relying to much on well behaved maven dependencies with META-INF/maven metadata filled in the jar. In those rogue cases if the dependency is available locally (i.e. in ~/.m2/repository for example) with a valid pom file (which is the case of these two dependencies) the plugin should use those. Truth is that the plugin was able to download the dependency inclusive the associated pom file. I've checked the zookeeper dependency and the pom file is not available in the jar file, I think that for the zookeeper dependency that was the cause of the problem.

I'm delivering an example project with three big repositories were most of what I've discussed can be reproduced (it's an evolution of the example provided for issue #1570). 

[acme.platform.tar.gz](https://github.com/bndtools/bndtools/files/560689/acme.platform.tar.gz)

I think it's a good "real world" maven example of the problems I'm facing with this plugin. I think this plugin is indeed a better alternative to a pure indexing solution with maven-index-plugin but is not able to deal (yet) with all the cases that can appear.

Concerning the attached file. the projects com.acme.platform\* should be imported as maven projects the rest as normal bnd projects. The bndrun files are located in the run project namely bnd.core.bndrun which has two of the described errors and bnd.sling.bndrun which has much more errors which I have not analysed thoroughly but should be similar to the previous ones.

Best Regards,
Ivo Leitão

**Comment by bjhargrave** [comment]
@pkriens Any status on this?

**Comment by pkriens** [comment]
https://github.com/bndtools/bnd/pull/2063
