### ISSUE TITLE
NPE using Bnd native launcher from within Eclipse.

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bndtools#1574]
When trying to launch an OSGi run definition or perform OSGi tests from the IDE I get the following NPE:

    java.lang.NullPointerException
    	at bndtools.launch.OSGiJUnitLaunchDelegate.getLauncherStatus(OSGiJUnitLaunchDelegate.java:77)
    	at bndtools.launch.AbstractOSGiLaunchDelegate.finalLaunchCheck(AbstractOSGiLaunchDelegate.java:99)
    	at bndtools.launch.OSGiJUnitLaunchDelegate.finalLaunchCheck(OSGiJUnitLaunchDelegate.java:64)
    	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:868)
    	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
    	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
    	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

I'm afraid I have no clue how to reproduce, as the exact same workspace cloned fresh from the same commit works on one computer but not another. I had just installed PyDev before it started happening, but uninstalling it didn't fix the problem and installing it on another machine didn't recreate the problem.

It is workspace-wide, but other workspaces opened with the same Eclipse installation are unaffected.

I can't glean anything from the offending line in `OSGiJUnitLaunchDelegate`:

    return createStatus("Problem(s) preparing the runtime environment.", bndTester.getProjectLauncher().getErrors(), bndTester.getProjectLauncher().getWarnings());

Version is latest: 3.4.0.DEV-20161102-194936-g37c29c8

**Comment by eliasvasylenko** [comment]
Deleting the bnd workspace and re-cloning didn't fix ... but deleting the eclipse workspace and recreating it did.

I also noticed PyDev sets to not build before launch, which does cause problems. It doesn't normally cause an NPE though.

**Comment by mnlipp** [comment]
The problem is the build before launch setting in Eclipse. If not set, `org.eclipse.debug.internal.core.LaunchConfiguration` does not invoke `OSGiRunLaunchDelegate.initialiseBndLauncher`. Due to this missing call, attribute `bndLauncher` is never initialized. So when eventually `OSGiRunLaunchDelegate.getLauncherStatus` is called, we get the NPE. (Reproduced with 3.3.0-REL)

**Comment by pkriens** [comment]
@mnlipp Could you make a patch to fix this? You seem to understand the problem well?

**Comment by mnlipp** [comment]
@pkriens I *seem* to have had an understanding one and a half years ago. But I haven't done anything with eclipse plugins for at least a year. I'll have a look again as soon as I find some time. However, from my description, I'd assume that this is an architectural issue that should be handled by whoever designed the plugin. The proper initialization of a plugin should not depend on a launch.
