### ISSUE TITLE
JUnit view shows wrong summary after running integration tests

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1586]
I used Bndtools 3.3.0.REL, to create this example integration test (using the _Integration Testing_ project template):

```java
public class ExampleIntegrationTest {
	@Test
	public void test1() throws Exception {
		assertTrue( false );
	}
	
	@Test
	public void test2() throws Exception {
		assertTrue( true );
	}
}
```
The bndrun file is this:
```
-runfw: org.apache.felix.framework;version=4
-runee: JavaSE-1.8
-runprovidedcapabilities: ${native_capability}

-resolve.effective: active;skip:="osgi.service"

-runrequires: \
	osgi.identity;filter:='(osgi.identity=org.example.itest)'
-runbundles: \
	org.apache.felix.http.servlet-api;version='[1.1.2,1.1.3)',\
	org.apache.felix.log;version='[1.0.1,1.0.2)',\
	org.apache.felix.scr;version='[2.0.2,2.0.3)',\
	org.example.itest;version=snapshot,\
	org.mockito.mockito-core;version='[1.10.19,1.10.20)',\
	org.objenesis;version='[2.2.0,2.2.1)',\
	osgi.enroute.hamcrest.wrapper;version='[1.3.0,1.3.1)',\
	osgi.enroute.junit.wrapper;version='[4.12.0,4.12.1)'
```

After running the projects as _OSGi Framework JUnit Tests_, I see this console output (which is correct):
```
Tests run  : 2
Passed     : 1
Errors     : 1
Failures   : 0
```
But the JUnit view shows this:
![image](https://cloud.githubusercontent.com/assets/607182/20649087/5df29c5a-b4b7-11e6-89ee-6db6839554c7.png)

Note that the progress bar is far from complete and the total number of tests are zero.

**Comment by bjhargrave** [comment]
Can you retest this on 3.4.0.DEV?

**Comment by rherrmann** [comment]
Yes, I will do so on Monday, when I am back to the environment where I encountered this issue.

**Comment by rherrmann** [comment]
This issue is still there with today's 3.4.0.DEV build.

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem?

**Comment by rherrmann** [comment]
I have created a repository here: https://github.com/rherrmann/bndtools-issue-1586
Please let me know if this is sufficient to reproduce the issue.

**Comment by bjhargrave** [comment]
Your bnd file is missing

```
Test-Cases: ${classes;CONCRETE;NAMED;*Test}
```

An integration test bundle must specify the `Test-Cases` manifest header with the names of the classes with test cases. When adding this, the test work as expected from gradle:

```
:org.example.integration.test:testOSGi
TEST test1(org.example.integration.test.ExampleIntegrationTest) <<< ERROR: null
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.example.integration.test.ExampleIntegrationTest.test1(ExampleIntegrationTest.java:11)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:342)
        at aQute.junit.Activator.automatic(Activator.java:228)
        at aQute.junit.Activator.run(Activator.java:171)
        at aQute.launcher.Launcher$5.call(Launcher.java:1201)
        at aQute.launcher.Launcher$5.call(Launcher.java:1199)
        at aQute.launcher.Launcher.run(Launcher.java:328)
        at aQute.launcher.Launcher.main(Launcher.java:138)
Tests run  : 2
Passed     : 1
Errors     : 1
Failures   : 0
error  : Exit code remote process 1: java -cp /Users/hargrave/.m2/repository/org/apache/felix/org.apache.felix.framework/5.4.0/org.apache.felix.framework-5.4.0.jar:/Users/hargrave/git/tmp/bndtools-issue-1586/cnf/cache/3.4.0/bnd-cache/biz.aQute.launcher/biz.aQute.launcher-3.4.0.jar -Dlauncher.properties="/Users/hargrave/git/tmp/bndtools-issue-1586/org.example.integration.test/generated/launch2867079801933632348.properties" -ea aQute.launcher.Launcher
:org.example.integration.test:testOSGi FAILED
```

**Comment by bjhargrave** [comment]
I think I see the issue. While the gradle output is correct, the xml report is not.
