### ISSUE TITLE
Many UnknownHostException after computer wakes up from stand by

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1587]
After resuming my computer from stand by while Eclipse with Bndtools 3.3.0.REL installed was running, I see this job error dialog

![image](https://cloud.githubusercontent.com/assets/607182/20651039/7f38933a-b4dd-11e6-89e0-4160f37112ef.png)

The full stack trace of one of such error is:
```
java.net.UnknownHostException: raw.githubusercontent.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at aQute.bnd.http.HttpClient.doConnect(HttpClient.java:483)
	at aQute.bnd.http.HttpClient.access$100(HttpClient.java:59)
	at aQute.bnd.http.HttpClient$2.call(HttpClient.java:302)
	at aQute.bnd.http.HttpClient$2.call(HttpClient.java:299)
	at aQute.bnd.http.HttpClient.connectWithProxy(HttpClient.java:392)
	at aQute.bnd.http.HttpClient.send0(HttpClient.java:299)
	at aQute.bnd.http.HttpClient.doCached0(HttpClient.java:230)
	at aQute.bnd.http.HttpClient.doCached(HttpClient.java:154)
	at aQute.bnd.http.HttpClient.send(HttpClient.java:130)
	at aQute.bnd.http.HttpRequest$1.run(HttpRequest.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by gamerson** [comment]
@rherrmann can you send the contents of this stacktrace that shows up in the Eclipse error log?  We need to see the enclosing Eclipse job that was executing this connection request so we can see who is polluting the UI with error dialogs.  We should just log these errors and find a better way that doesn't interrupt the user.  

Also in 3.4 dev builds we have an 'offline' mode for Bndtools (found in the repositories view) where you can tell bnd that "Hey stop trying to connect to the internet, i'm offline"

![screen shot 2016-11-28 at 10 15 03 am](https://cloud.githubusercontent.com/assets/595221/20675960/b7fdb562-b553-11e6-892f-7addb32fd541.png)

**Comment by rherrmann** [comment]
@gamerson I will try to give more information when I see this again. Though I think there wasn't a job name mentioned. But I will amend the given information with what I find.

Thanks for the offline mode hint. I don't know what the offline mode is intended for, however, in the situation described here (wake up from standby), I don't think it would help. 

When logging connection problems, you may also want to make sure that repeated errors are only logged when they occur for the first time, thus preventing the error log from filling up with equal entries.

Unrelated to this issue, I have seen info messages logged every five or so minutes, saying e.g. 'Download https://raw.githubusercontent.com/bndtools/bundle-hub/master/index.xml.gz'. This makes it difficult finding relevant information in the log. Please let me know if you would consider this something to change and if you would want me to open a separate bug entry.

**Comment by rherrmann** [comment]
I can't make out the job name that causes the `UnknownHostException`. In case I've missed something, I've attached a screenshot of the event details:
![image](https://cloud.githubusercontent.com/assets/607182/20726595/967d438e-b676-11e6-80f3-0b4c5ab21a8a.png)

I've also exported the event log, please let me know if I should send it to you.

**Comment by MarkJeronimus** [comment]
This turned up in a Google search so I thought I'd give my thoughts.

I'm developing a small stand-alone Java application that continuously sends web requests. After my computer woke from stand-by while it was running, I got an UnknownHostException. It seems it's a Java thing and has nothing to do with bndtools. (except the fact that bndtools might handle them in a more user-friendly way)
