### ISSUE TITLE
ConcurrentModificationException in bnd build job

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1610]
While editing one of the `.bnd` files in the workspace configuration (`cnf/ext/`), I saw this error thrown by a build job that runs after saving:

> An internal error occurred during: "Refresh Workspace Repository".

I am afraid, I can't provide steps to reproduce the error. However, I will post further findings here, if there are.

In the meanwhile the stacktrace may help tracking down the issue:
```
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
	at aQute.bnd.osgi.Processor.getPlugins(Processor.java:478)
	at bndtools.central.WorkspaceRepositoryChangeDetector$1.runInWorkspace(WorkspaceRepositoryChangeDetector.java:129)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by bjhargrave** [comment]
I'm making a PR to fix this in the bnd repo.
