### ISSUE TITLE
Bnd/Bndtools cannot resolve certain artifacts from maven repository

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1634]
Environment
---
In a workspace with two projects, `cnf` and `example`, Bndtools 3.4.0.DEV cannot resolve certain libraries from _Maven Central_. 

The `cnf/build.bnd` file has this content:
```
-plugin: \
    aQute.bnd.repository.osgi.OSGiRepository; \
        name=Bndtools Hub; \
        locations=https://raw.githubusercontent.com/bndtools/bundle-hub/master/index.xml.gz; \
    , \
    aQute.bnd.repository.maven.pom.provider.BndPomRepository; \
        releaseUrls=https://repo1.maven.org/maven2/; \
        pom=${workspace}/cnf/maven-central.xml; \
        name=Maven Central;
```

The `cnf/maven-central.xml` looks like this:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>

  <groupId>local</groupId>
  <artifactId>maven-central</artifactId>
  <version>0.0.0</version>
  <packaging>pom</packaging>
	
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>2.6</version>
    </dependency>
  </dependencies>

</project>
```

The example project has a  `bnd.bnd` file with this content:
```
-testpath: junit:junit;version=latest,\
    org.mockito:mockito-core;version=latest
```

Problem
---
The `bnd.bnd` file of the example project shows these three error markers (all on line 1 of the bnd file)
> Exception: java.io.IOException: The parameter is incorrect
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.Win32FileSystem.canonicalize(Win32FileSystem.java:414)
	at java.io.File.getCanonicalPath(File.java:618)
	at java.io.File.getCanonicalFile(File.java:643)
	at bndtools.central.Central.toPath(Central.java:417)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.fileToPath(BndContainerInitializer.java:647)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.calculateContainersClasspath(BndContainerInitializer.java:404)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.calculateProjectClasspath(BndContainerInitializer.java:357)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.access$0(BndContainerInitializer.java:343)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater$1.call(BndContainerInitializer.java:260)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater$1.call(BndContainerInitializer.java:1)
	at bndtools.central.Central.bndCall(Central.java:626)
	at bndtools.central.Central.bndCall(Central.java:591)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer(BndContainerInitializer.java:257)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:122)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:167)
	at org.bndtools.builder.BndtoolsBuilder.requestClasspathContainerUpdate(BndtoolsBuilder.java:408)
	at org.bndtools.builder.BndtoolsBuilder.access$6(BndtoolsBuilder.java:397)
	at org.bndtools.builder.BndtoolsBuilder$1.call(BndtoolsBuilder.java:185)
	at org.bndtools.builder.BndtoolsBuilder$1.call(BndtoolsBuilder.java:1)
	at bndtools.central.Central.bndCall(Central.java:626)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:127)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

> Failed to convert file java.io.FileNotFoundException: For Maven artifact org.mockito:mockito-core:2.6
	at aQute.maven.provider.MavenRepository$1.run(MavenRepository.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
: null to Eclipse path: The parameter is incorrect

> Repository file java.io.FileNotFoundException: For Maven artifact org.mockito:mockito-core:2.6
	at aQute.maven.provider.MavenRepository$1.run(MavenRepository.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
: null does not exist

On the `cnf` project there is one error marker,
> The project cannot be built until build path errors are resolved

No additional information is given.

To make things worse, the error markers on the example project sometimes vanish after making changes like adding or changing a Java source file. After invoking _Project_ > _Clean_, the above noted error markers re-appear.

The _Repositories_ view shows both repositories. The Mockito library is even present in both repositories: v2.6 in the Maven repository and v 1.x in Bndtools Hub. The unresolvable entries are decorated with an exclamation mark _[!]_ and _NullPointerException_

![image](https://cloud.githubusercontent.com/assets/607182/22216130/24c19f6c-e19e-11e6-98b5-744798b94499.png)

**Comment by bjhargrave** [comment]
There is no 

```xml
<dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>2.6</version>
</dependency>
```
There is a version `2.6.0`. Maven is does not canonicalize version numbers, so you must specify them exactly. Using `2.6.0` as the version number works as expected.

**Comment by rherrmann** [comment]
A clear message instead of `[!] NullPointerException` or an exception turned into an error marker would of course be helpful here.
