### ISSUE TITLE
Eclipse becomes unresponsive after expanding item in Repository view

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1637]
I have added a p2 repository to a global bnd file in `cnf/ext` like this:

```
-plugin: \
    aQute.bnd.repository.p2.provider.P2Repository; \
        name="Eclipse Orbit"; \
        url=http://download.eclipse.org/tools/orbit/downloads/drops/R20160520211859/repository/; \
```

The host serving the repository isn't particularly fast and to make things worse, my internet connection also became unreliable.

After saving the bnd file, I opened the _Repository_ view and expanded the newly added item. An hour-glass cursor appeared and the UI thread was blocked. No other UI interaction was possible. A minute or so later a Job error dialog revealed the cause of the unresponsiveness:

![image](https://cloud.githubusercontent.com/assets/607182/22371378/2c8d4330-e497-11e6-9c28-770efdb35e22.png)

This scenario can also be simulated when disconnecting the computer from the network.

On a related note, I saw an exception with the message 'Failed to refresh plugins' being reported:

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at aQute.bnd.repository.p2.provider.P2Repository.getP2Index0(P2Repository.java:72)
	at aQute.bnd.repository.p2.provider.P2Repository.getP2Index(P2Repository.java:53)
	at aQute.bnd.repository.p2.provider.P2Repository.refresh(P2Repository.java:120)
	at bndtools.central.Central.refreshPlugins(Central.java:469)
	at bndtools.views.repository.RepositoriesView$11$1.runInWorkspace(RepositoriesView.java:585)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.reflect.InvocationTargetException
	at org.osgi.util.promise.PromiseImpl.getValue(PromiseImpl.java:159)
	at aQute.p2.provider.P2Impl.getArtifacts(P2Impl.java:63)
	at aQute.bnd.repository.p2.provider.P2Indexer.readRepository(P2Indexer.java:133)
	at aQute.bnd.repository.p2.provider.P2Indexer.<init>(P2Indexer.java:70)
	at aQute.bnd.repository.p2.provider.P2Repository.getP2Index0(P2Repository.java:70)
	... 6 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at aQute.bnd.http.HttpClient.doConnect(HttpClient.java:486)
	at aQute.bnd.http.HttpClient.access$100(HttpClient.java:61)
	at aQute.bnd.http.HttpClient$2.call(HttpClient.java:305)
	at aQute.bnd.http.HttpClient$2.call(HttpClient.java:302)
	at aQute.bnd.http.HttpClient.connectWithProxy(HttpClient.java:395)
	at aQute.bnd.http.HttpClient.send0(HttpClient.java:302)
	at aQute.bnd.http.HttpClient.doCached0(HttpClient.java:263)
	at aQute.bnd.http.HttpClient.doCached(HttpClient.java:157)
	at aQute.bnd.http.HttpClient.send(HttpClient.java:133)
	at aQute.bnd.http.HttpRequest$1.run(HttpRequest.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
Seems that the refresh code gets confused by the delayed repository download as well.

**Comment by gamerson** [comment]
As discussed with the Bndtools committers, the plan is to throttle the updates to the Eclipse UI Progress View so it doesn't cause the UI to be too busy.
