### ISSUE TITLE
When first opening .bnd file, Build Path is blank

### ISSUE THREAD

**Issue by wodencafe** [bndtools/bndtools#1713]
When I first open Eclipse and open up my .bnd file, on the Build tab, which happened to be the last one I had selected, the Build Path is blank, as seen below: 

![screenshot_20170527_204356](https://cloud.githubusercontent.com/assets/9727493/26525458/3d6e883c-431d-11e7-9f9b-5d66dcee59c8.png)

Also at the top, the message "Workspace is loading, please wait..." and a Warning icon are shown, and these do not go away by waiting.

The Build Path only appears when I either press "Rebuild Project", or navigate to the "Contents" or "Run" tabs of the bnd file and navigate back. Doing any of these things also clear the Warning icon and "Workspace is loading, please wait..." message.

![desktop-animation](https://cloud.githubusercontent.com/assets/9727493/26525493/741f0e46-431e-11e7-8698-c1abbb2281b4.gif)

Also, every time I click the message "Workspace is loading, please wait..." an "Unhandled event loop exception" occurs in the Error Log:

![desktop-animation](https://cloud.githubusercontent.com/assets/9727493/26525556/25076298-4320-11e7-9ff4-d971276829da.gif)

Here is the error that is produced:
```

java.lang.NullPointerException
	at bndtools.utils.MessagesPopupDialog.createDialogArea(MessagesPopupDialog.java:72)
	at org.eclipse.jface.dialogs.PopupDialog.createContents(PopupDialog.java:694)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.PopupDialog.open(PopupDialog.java:1141)
	at bndtools.utils.MessageHyperlinkAdapter.showPopup(MessageHyperlinkAdapter.java:44)
	at bndtools.utils.MessageHyperlinkAdapter.linkActivated(MessageHyperlinkAdapter.java:30)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:228)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:322)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.access$2(AbstractHyperlink.java:306)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink$4.handleEvent(AbstractHyperlink.java:129)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

System Info:
```
Bndtools 3.3.0.REL-20160922
openjdk version "1.8.0_131"
Ubuntu 17.04 zesty
Kernel 4.10.0-21-generic
```

**Comment by seanbright** [comment]
Can you try to reproduce with 3.4.0.DEV?

**Comment by gamerson** [comment]
the NPE has been fixed https://github.com/bndtools/bndtools/commit/c63064d17fcd296283605c349446b356f4d9fdfb

But the other issues likely remain.
