### ISSUE TITLE
bndtools adds bundle twice to exported jar.

### ISSUE THREAD

**Issue by aploese** [bndtools/bndtools#1737]
The bnd_corrupt.bnd.txt is the bnd which produces the faulty jar.
Here is the command line with the stack trace:
java -jar FHZ-DS.jar 
! Unexpected error in the run body: A bundle is already installed with the name "de.ibapl.papaya.ds.fhz.provider" and version "1.0.0.201706281902"
org.osgi.framework.BundleException: A bundle is already installed with the name "de.ibapl.papaya.ds.fhz.provider" and version "1.0.0.201706281902"
	at org.eclipse.osgi.container.ModuleContainer.install(ModuleContainer.java:254)
	at org.eclipse.osgi.storage.Storage.install(Storage.java:516)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:146)
	at aQute.launcher.Launcher.installEmbedded(Launcher.java:661)
	at aQute.launcher.Launcher.update(Launcher.java:446)
	at aQute.launcher.Launcher.activate(Launcher.java:400)
	at aQute.launcher.Launcher.run(Launcher.java:283)
	at aQute.launcher.Launcher.main(Launcher.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:44)
org.osgi.framework.BundleException: A bundle is already installed with the name "de.ibapl.papaya.ds.fhz.provider" and version "1.0.0.201706281902"
	at org.eclipse.osgi.container.ModuleContainer.install(ModuleContainer.java:254)
	at org.eclipse.osgi.storage.Storage.install(Storage.java:516)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:146)
	at aQute.launcher.Launcher.installEmbedded(Launcher.java:661)
	at aQute.launcher.Launcher.update(Launcher.java:446)
	at aQute.launcher.Launcher.activate(Launcher.java:400)
	at aQute.launcher.Launcher.run(Launcher.java:283)
	at aQute.launcher.Launcher.main(Launcher.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:44)

launcher.properties and MANIFEST.MF are from the faulty jar.  
The bnd.bnd produces a runnable jar.

[bnd.bnd.txt](https://github.com/bndtools/bndtools/files/1109959/bnd.bnd.txt)
[bnd_corrupt.bnd.txt](https://github.com/bndtools/bndtools/files/1109958/bnd_corrupt.bnd.txt)
[launcher.properties.txt](https://github.com/bndtools/bndtools/files/1109960/launcher.properties.txt)
[MANIFEST.MF.txt](https://github.com/bndtools/bndtools/files/1109961/MANIFEST.MF.txt)

**Comment by bjhargrave** [comment]
Closing. Please open a new issue if this is still a problem with a small github repo which demonstrates the problem? Then we can investigate.
