### ISSUE TITLE
NPE in m2e IndexConfigurator

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#1807]
This was in Bndtools 4.0.0.DEV-20171117-161727-g05f8a7a. It happened when I was doing a Maven Update (Alt-F5) of all projects.

```
java.lang.NullPointerException
	at bndtools.m2e.IndexConfigurator$RebuildIndexCheck.needsBuild(IndexConfigurator.java:176)
	at bndtools.m2e.IndexConfigurator$RebuildIndexCheck.runInWorkspace(IndexConfigurator.java:162)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by njbartlett** [comment]
I tracked this down. On line 161 of IndexConfigurator.java, we ask for the `IMavenProjectFacade` for each referenced project. It appears that Eclipse was holding onto a stale reference to a project that had disappeared as the result of some git shenanigans... so the IMavenProjectFacade came back as null. A simple null-check just after line 161 should fix this.
