### ISSUE TITLE
NPE when I created a new bndrun file (Bndtools 3.5.0.REL)

### ISSUE THREAD

**Issue by wodencafe** [bndtools/bndtools#1812]
Hi guys,

I encountered the following NPE when I created a new BND Run Descriptor file in my project:
![ezgif-3-c041fa4e76](https://user-images.githubusercontent.com/9727493/33243702-9d14c102-d2b0-11e7-88f0-378ddda04016.gif)

```
java.lang.NullPointerException
	at bndtools.editor.project.RepositorySelectionPart.resourceChanged(RepositorySelectionPart.java:539)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:157)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

```
```
eclipse.buildId=4.7.1.M20171009-0410
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product
```
`  Bndtools	3.5.0.REL-20170929-190052-ga0d7a6b	bndtools.main.feature.feature.group	Bndtools`

**Comment by bjhargrave** [comment]
@gamerson Can you look into this?
