### ISSUE TITLE
[m2e] when doing many quick code changes the IDE will often crash completely

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bndtools#1831]
When iterating through several quick changes to bndtools.m2e projects (i.e. code change, save, code change, save, and so on...) the IDE will often completely crash (total JVM shutdown).

Here's the error
```
java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:583)
	at java.util.zip.ZipFile.access$900(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:539)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:514)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at aQute.bnd.osgi.Jar.buildFromZip(Jar.java:172)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:89)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:115)
	at bndtools.m2e.BndConfigurator$MavenProjectInfo.<init>(BndConfigurator.java:70)
	at bndtools.m2e.BndConfigurator$2.call(BndConfigurator.java:198)
	at bndtools.m2e.BndConfigurator$2.call(BndConfigurator.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at bndtools.m2e.BndConfigurator.execJarMojo(BndConfigurator.java:179)
	at bndtools.m2e.BndConfigurator.access$000(BndConfigurator.java:51)
	at bndtools.m2e.BndConfigurator$1$1.runInWorkspace(BndConfigurator.java:127)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by gamerson** [comment]
Discussed with @rotty3000 separately and we made the following observations:

1) This problem seems easiest to happen when we introduce a compilation error in one of the class files, and the jar:jar goal is executed regardless, which brings up the question. **Should we actually short-circuit the BndConfigurator calling the jar:jar goal when we encounter other build errors?**
2) Because of the indeterminate nature of reproducing this bug, we are assuming it is a concurrency problem.  One potential culprit is the BndConfigurator's use of a WorkspaceJob to execute the jar:jar goal instead of executing it directly.  This async behavior leaves open the door that some other agent is doing something to the jar before we can read the project info.  **Should we investigate re-designing the BndConfigurator to not execute the jar:jar goal asynchronously and instead try to reconfigure the m2e lifecycle mappings to declare to m2e that we want the jar:jar goal executed after bnd-process for all incremental builds?**

**Comment by bjhargrave** [comment]
![image](https://user-images.githubusercontent.com/277682/36118217-4821e6ba-100a-11e8-8f04-27bcb1f4e300.png)

**Comment by rotty3000** [comment]
Oops, I noticed that this is a dup of #1857 
Since I associated a fix with the other one, I'll close this one.
