### ISSUE TITLE
Windows: Build fails out-of-box when home directory is redirected to a network share

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bndtools#1834]
Hello all,

I pray everyone is well.

I have just started playing with bndtools (great project, by the way). My environment is:
* Windows 10
* jdk 1.8.0_131
* bndtools HEAD (specifically: `4.0.0.DEV-20180215-210111-g9a8b134`).

Our corporate environment includes group policies that redirects our home directory to a network share. 

When I import bndtools to start working on it, I get a ton of build errors with a root error of:

````
bndtools.bndplugins.repos: Exception: java.nio.file.InvalidPathException: Illegal character [:] in path at index 10: \\server/C:/Program Files/Java/jdk1.8.0_131/jre/lib/rt.jar
	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:116)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsUriSupport.fromUri(WindowsUriSupport.java:165)
	at sun.nio.fs.WindowsFileSystemProvider.getPath(WindowsFileSystemProvider.java:92)
	at java.nio.file.Paths.get(Paths.java:138)
	at aQute.bnd.osgi.Resource.fromURL(Resource.java:38)
	at aQute.bnd.osgi.Analyzer.findClass(Analyzer.java:2830)
	at aQute.bnd.xmlattribute.XMLAttributeFinder.getXMLAttribute(XMLAttributeFinder.java:30)
	at aQute.bnd.metatype.OCDReader$OCDDataCollector.annotation(OCDReader.java:165)
	at aQute.bnd.osgi.Clazz.doAnnotations(Clazz.java:1517)
	at aQute.bnd.osgi.Clazz.doAttribute(Clazz.java:987)
	at aQute.bnd.osgi.Clazz.doAttributes(Clazz.java:966)
	at aQute.bnd.osgi.Clazz.parseClassFileData(Clazz.java:764)
	at aQute.bnd.osgi.Clazz.parseClassFileData(Clazz.java:508)
	at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:493)
	at aQute.bnd.metatype.OCDReader.getDef(OCDReader.java:58)
	at aQute.bnd.metatype.OCDReader.getOCDDef(OCDReader.java:54)
	at aQute.bnd.metatype.MetatypeAnnotations.analyzeJar(MetatypeAnnotations.java:110)
	at aQute.bnd.osgi.Analyzer.doPlugins(Analyzer.java:746)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:220)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:386)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:776)
	at aQute.bnd.osgi.Builder.build(Builder.java:107)
	at aQute.bnd.osgi.Builder.builds(Builder.java:1295)
	at aQute.bnd.build.ProjectBuilder.builds(ProjectBuilder.java:578)
	at aQute.bnd.build.Project.buildLocal(Project.java:1802)
	at aQute.bnd.build.Project.build(Project.java:1619)
	at aQute.bnd.build.Project.build(Project.java:2240)
	at org.bndtools.builder.BndtoolsBuilder.lambda$build$0(BndtoolsBuilder.java:242)
	at bndtools.central.Central.bndCall(Central.java:627)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:122)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
````

...where `server` is the internal name of our file server where the redirected home folders are pointed.

It seems that, at some point, bndtools is making an assumption about the path structure which doesn't take this possibility into account. I also think it's a bit strange that my home directory path somehow gets tangled up with an attempt to calculate the path to `JAVA_HOME`.

**Comment by bjhargrave** [comment]
The code in question: 

https://github.com/bndtools/bnd/blob/54fde777a0a5c737a095d2263a03eec34bdc3bf9/biz.aQute.bndlib/src/aQute/bnd/osgi/Resource.java#L38

`Path path = Paths.get(Paths.get("").toUri().resolve(jarFileURL.getPath()));`

is trying to resolve the jar path against the working directory (`Paths.get("").toUri()`) since the jar path could be relative. I am not sure how your home directory come into play unless your working directory is inside your home directory.

I don't have a windows system, so I cannot even begin to know how to debug UNC path issues here. Perhaps you can do some experiments with code like this to figure out a more robust solution for windows?

**Comment by kriegfrj** [comment]
I understand that this issue will be difficult for you to debug without a system to test it on.

I'm willing to have a bit of a play to see what's happening as it will probably be a simple fix (especially now that you've pointed me in the right direction with the code). However, I have issue is that I have a bootstrapping issue - I can't run any tests on my system until I have successfully built it on my system, but it will be difficult to achieve a successful build at the moment because of this issue. Is there some configuration setting where I can manually override the temp/default path on my installed version without having to rebuild it?

**Comment by bjhargrave** [comment]
I was not suggesting you build Bnd with code changes. I was suggested you take that snippet of code into a small java class and experiment on your system.

**Comment by kriegfrj** [comment]
> I was not suggesting you build Bnd with code changes. I was suggesting you take that snippet of code 
> into a small java class and experiment on your system.

😊 That would have made sense - my apologies, I should have done that.

Just confirming that I have installed the latest snapshot since bndtools/bnd#2321 and it is now building successfully on my machine. Thanks for the fix.
