### ISSUE TITLE
Bndtools build dying

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bndtools#1862]
Porting a project to Bndtools, something has happened which has rendered the entire Bndtools aspect inoperable (Repositories won't display, artifacts won't build, etc).

Getting "info" level errors in the error log (arguably, the severity should be higher):

````
eclipse.buildId=unknown
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_AU

bndtools.builder
Info
Tue Mar 20 15:32:10 ACDT 2018
Unable to get bnd project for project org.apache.ecs

java.nio.file.FileAlreadyExistsException: C:\workspace\idempiere-bndtools\org.adempiere.ui.zk\WEB-INF\web.xml
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:81)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at aQute.lib.io.IO.mkdirs(IO.java:769)
	at aQute.lib.io.IO.mkdirs(IO.java:762)
	at aQute.bnd.build.Project.prepare(Project.java:324)
	at aQute.bnd.build.Project.getDependson(Project.java:839)
	at aQute.bnd.build.Workspace.getBuildOrder(Workspace.java:562)
	at bndtools.central.Central.getWorkspace(Central.java:251)
	at bndtools.central.Central.getProject(Central.java:573)
	at bndtools.central.Central.getProject(Central.java:577)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.<init>(BndContainerInitializer.java:207)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:104)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:151)
	at org.bndtools.builder.classpath.BndContainerCompilationParticipant.aboutToBuild(BndContainerCompilationParticipant.java:19)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:592)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:169)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
````

I first noticed this when I started trying to open the Repositories pane and the repositories wouldn't expand to show me the bundles. Since I restarted Eclipse, the Repositories pane has sat there saying "Repositories are loading, please wait..."

1. The file does already exist, but I'm not sure it should matter; 
2. Even if the file does exist, Bndtools should be more graceful about handling it, or at the very least louder about the fact that it isn't handling it (eg, the Repositories pane by now should have said "Error trying to load the repositories, see error log for details" or something like that.

**Comment by kriegfrj** [comment]
The root cause of this was fixed in bndtools/bnd#2380, but it would still be nice if Bndtools was nicer/louder about the fact that Bnd has failed.

**Comment by bjhargrave** [comment]
Closing since there was a fix in Bnd.

**Comment by kriegfrj** [comment]
I'd be tempted to leave this open, perhaps with a name change. Yes the root problem in bnd was fixed, but IMHO it is still an issue that bndtools didn't handle the fatal error in Bnd and didn't even report that an error had occurred. Your call though.
