### ISSUE TITLE
NPE refreshing Browse Repos viewer in bndrun editor

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#1921]
Seen in version 4.1.0.DEV (latest HEAD).

```
java.lang.NullPointerException
	at bndtools.model.repo.RepositoryTreeContentProvider$1.run(RepositoryTreeContentProvider.java:314)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

(yeah that's the full stack trace...)

Note the Browse Repos viewer still populates a second later, so maybe this is a race.

**Comment by njbartlett** [comment]
<img width="851" alt="screen shot 2018-08-14 at 07 00 22" src="https://user-images.githubusercontent.com/6366/44074244-c7dc20c2-9f8f-11e8-98c3-ea25ec978069.png">
