### ISSUE TITLE
Lacking proxy support on Eclipse/Windows for native proxy provider

### ISSUE THREAD

**Issue by peterkir** [bndtools/bndtools#450]
Using Windows7 64-bit with Eclipse 3.7.2, 3.8, 4.2

When starting a windows eclipse version per default the native proxy provider is used.
This works fine for updating and installing BNDtools.

But as soon as you create the cnf project it is not possible to connect to the BNDtools Hub.

Workaround: Configure the proxy manual

It is really a minor issue, but very confusing for users cause installing works (which means my internet connection is fine), but BNDtools is not able to download the remote sources.

**Comment by asardaes** [comment]
Well this issue is pretty old, are there any plans to address this?

I realize that the Hub is deprecated, but I guess this would be a more general connection problem. Right now, trying to follow the basic Bndtools tutorial, I can't access the repository, and trying to update just results in:

```
Failed to refresh plugins

java.lang.NullPointerException
	at aQute.bnd.repository.osgi.OSGiIndex.download(OSGiIndex.java:87)
	at aQute.bnd.repository.osgi.OSGiIndex.readIndexes(OSGiIndex.java:59)
	at aQute.bnd.repository.osgi.OSGiIndex.<init>(OSGiIndex.java:52)
	at aQute.bnd.repository.osgi.OSGiRepository.getIndex(OSGiRepository.java:154)
	at aQute.bnd.repository.osgi.OSGiRepository.refresh(OSGiRepository.java:270)
	at bndtools.central.Central.refreshPlugins(Central.java:466)
	at bndtools.views.repository.RepositoriesView$10$1.runInWorkspace(RepositoriesView.java:536)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

I manually configured the proxy in Eclipse and it is capable of accessing the Marketplace, since I got Bndtools from there. Are there any workarounds?

**Comment by bjhargrave** [comment]
Did you look at http://bnd.bndtools.org/instructions/connection-settings.html. Bnd supports proxy now.

**Comment by asardaes** [comment]
Do you know if it supports [Maven's password encryption within the `settings.xml` file](https://maven.apache.org/guides/mini/guide-encryption.html)?

**Comment by bjhargrave** [comment]
I highly doubt it. That whole thing seems pretty unsafe since it can produce the original master password.
