### ISSUE TITLE
Copy to clipboard does not always work.

### ISSUE THREAD

**Issue by derheld42** [bndtools/bndtools#525]
Built bndtools from source. Running 1f3639e2dfe36f5933505babb8df9a605e0f1d50 version of bndtools (8/24/2012). It's pulling from the remote repo i.e. I didn't adjust any bndtools code/configs.

I had a simple Junit test that was getting a resolution error like:
Unable to resolve <<INITIAL>> ver=null: missing requirement (osgi.identity=top)
Unable to resolve <<INITIAL>> ver=null: missing requirement (osgi.identity=top)

I am not able to use the copy to clipboard button on the resolution results window. I was able to double click on the error, then right click on the message and select "copy". How the button on the resolution results window doesn't seem to always work.

ResolutionFailurePanel.java:260 -- The StringBuilder variable had no content. I'm sure this is why this was happening. And of course there's a large TODO comment block above it.

java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:3865)
	at org.eclipse.swt.SWT.error(SWT.java:3799)
	at org.eclipse.swt.SWT.error(SWT.java:3770)
	at org.eclipse.swt.dnd.DND.error(DND.java:282)
	at org.eclipse.swt.dnd.DND.error(DND.java:228)
	at org.eclipse.swt.dnd.Clipboard.setContents(Clipboard.java:448)
	at org.eclipse.swt.dnd.Clipboard.setContents(Clipboard.java:379)
	at org.bndtools.core.resolve.ui.ResolutionFailurePanel.copyUnresolvedToClipboard(ResolutionFailurePanel.java:260)
	at org.bndtools.core.resolve.ui.ResolutionFailurePanel.access$0(ResolutionFailurePanel.java:231)
	at org.bndtools.core.resolve.ui.ResolutionFailurePanel$2.widgetSelected(ResolutionFailurePanel.java:203)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:228)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1176)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3493)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3112)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at bndtools.editor.project.RunRequirementsPart$8.run(RunRequirementsPart.java:334)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3468)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3115)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2405)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2369)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2221)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:500)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:493)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:113)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:194)
	at bndtools.eclipse.applaunch.BndApplicationLauncher$1.run(BndApplicationLauncher.java:37)
	at aQute.launcher.Launcher.run(Launcher.java:165)
	at aQute.launcher.Launcher.main(Launcher.java:69)

Test case -- project called "top":
test/Test1.java:
```
package test;
import junit.framework.TestCase;
public class Test1 extends TestCase {
   public void testSuccess() {
      assertEquals(true, true);
   }
   public void testFail() {
      assertEquals(true, false);
   }
}
```

ccc.bndrun:
```
-runfw: org.apache.felix.framework;version='[4,5)'
-runee: JavaSE-1.6
-runrequires: osgi.identity;filter:='(osgi.identity=top)'
```

bnd.bnd:
```
Private-Package: test
-buildpath: junit.osgi
Test-Cases: test.Test1
-runfw: org.apache.felix.framework;version='[4.0.3,4.0.3]'
-runee: JavaSE-1.7
```

The resolution error occurred when trying to do a resolve on the ccc.bndrun file. The copy to clipboard didn't work and left an error message in my eclipse .metadata/.log file.

**Comment by derheld42** [comment]
The new resolution dialog doesn't have the same button. And you can copy text from the error message. Closing out.
